// Generated by docs/htsp-protocol/generate_typed_server_messages.py. DO NOT EDIT.
// docs/htsp-protocol/htsp_surface.py is the reviewed finite dispatch authority.
package at.bernhardberger.tvheadend.htsp.messages

private data class TypedHtspServerMessageCatalogEntry(
    val method: String,
    val messageType: String,
    val minimumProtocolVersion: Int?,
)

private val typedHtspServerMessageCatalog: List<TypedHtspServerMessageCatalogEntry> = listOf(
    TypedHtspServerMessageCatalogEntry("channelAdd", "HtspChannelAddMessage", null),
    TypedHtspServerMessageCatalogEntry("channelUpdate", "HtspChannelUpdateMessage", null),
    TypedHtspServerMessageCatalogEntry("channelDelete", "HtspChannelDeleteMessage", null),
    TypedHtspServerMessageCatalogEntry("tagAdd", "HtspTagAddMessage", null),
    TypedHtspServerMessageCatalogEntry("tagUpdate", "HtspTagUpdateMessage", null),
    TypedHtspServerMessageCatalogEntry("tagDelete", "HtspTagDeleteMessage", null),
    TypedHtspServerMessageCatalogEntry("dvrEntryAdd", "HtspDvrEntryAddMessage", 4),
    TypedHtspServerMessageCatalogEntry("dvrEntryUpdate", "HtspDvrEntryUpdateMessage", 4),
    TypedHtspServerMessageCatalogEntry("dvrEntryDelete", "HtspDvrEntryDeleteMessage", 4),
    TypedHtspServerMessageCatalogEntry("autorecEntryAdd", "HtspAutorecEntryAddMessage", 13),
    TypedHtspServerMessageCatalogEntry("autorecEntryUpdate", "HtspAutorecEntryUpdateMessage", 13),
    TypedHtspServerMessageCatalogEntry("autorecEntryDelete", "HtspAutorecEntryDeleteMessage", 13),
    TypedHtspServerMessageCatalogEntry("timerecEntryAdd", "HtspTimerecEntryAddMessage", 18),
    TypedHtspServerMessageCatalogEntry("timerecEntryUpdate", "HtspTimerecEntryUpdateMessage", 18),
    TypedHtspServerMessageCatalogEntry("timerecEntryDelete", "HtspTimerecEntryDeleteMessage", 18),
    TypedHtspServerMessageCatalogEntry("eventAdd", "HtspEventAddMessage", 6),
    TypedHtspServerMessageCatalogEntry("eventUpdate", "HtspEventUpdateMessage", 6),
    TypedHtspServerMessageCatalogEntry("eventDelete", "HtspEventDeleteMessage", 6),
    TypedHtspServerMessageCatalogEntry("initialSyncCompleted", "HtspInitialSyncCompletedMessage", 2),
    TypedHtspServerMessageCatalogEntry("muxpkt", "HtspMuxPacketMessage", null),
    TypedHtspServerMessageCatalogEntry("queueStatus", "HtspQueueStatusMessage", null),
    TypedHtspServerMessageCatalogEntry("subscriptionStart", "HtspSubscriptionStartMessage", null),
    TypedHtspServerMessageCatalogEntry("subscriptionStop", "HtspSubscriptionStopMessage", null),
    TypedHtspServerMessageCatalogEntry("subscriptionGrace", "HtspSubscriptionGraceMessage", 13),
    TypedHtspServerMessageCatalogEntry("subscriptionStatus", "HtspSubscriptionStatusMessage", null),
    TypedHtspServerMessageCatalogEntry("signalStatus", "HtspSignalStatusMessage", null),
    TypedHtspServerMessageCatalogEntry("descrambleInfo", "HtspDescrambleInfoMessage", 24),
    TypedHtspServerMessageCatalogEntry("subscriptionSpeed", "HtspSubscriptionSpeedMessage", 9),
    TypedHtspServerMessageCatalogEntry("timeshiftStatus", "HtspTimeshiftStatusMessage", 9),
    TypedHtspServerMessageCatalogEntry("subscriptionSkip", "HtspSubscriptionSkipMessage", 9),
)

public sealed interface HtspServerMessageDecodeResult
public data class HtspServerMessageDecoded(
    public val message: HtspServerMessage,
) : HtspServerMessageDecodeResult
public data object HtspServerMessageUnknownMethod : HtspServerMessageDecodeResult
public data object HtspServerMessageMalformedKnownMessage : HtspServerMessageDecodeResult

public fun decodeHtspServerMessage(fields: Map<String, Any?>): HtspServerMessageDecodeResult {
    if (fields.containsKey("seq")) return HtspServerMessageUnknownMethod
    val method = fields["method"] as? String
        ?: return HtspServerMessageUnknownMethod
    return when (method) {
        "channelAdd" -> decodeKnownServerMessage { decodeChannelAdd(fields) }
        "channelUpdate" -> decodeKnownServerMessage { decodeChannelUpdate(fields) }
        "channelDelete" -> decodeKnownServerMessage { decodeChannelDelete(fields) }
        "tagAdd" -> decodeKnownServerMessage { decodeTagAdd(fields) }
        "tagUpdate" -> decodeKnownServerMessage { decodeTagUpdate(fields) }
        "tagDelete" -> decodeKnownServerMessage { decodeTagDelete(fields) }
        "dvrEntryAdd" -> decodeKnownServerMessage { decodeDvrEntryAdd(fields) }
        "dvrEntryUpdate" -> decodeKnownServerMessage { decodeDvrEntryUpdate(fields) }
        "dvrEntryDelete" -> decodeKnownServerMessage { decodeDvrEntryDelete(fields) }
        "autorecEntryAdd" -> decodeKnownServerMessage { decodeAutorecEntryAdd(fields) }
        "autorecEntryUpdate" -> decodeKnownServerMessage { decodeAutorecEntryUpdate(fields) }
        "autorecEntryDelete" -> decodeKnownServerMessage { decodeAutorecEntryDelete(fields) }
        "timerecEntryAdd" -> decodeKnownServerMessage { decodeTimerecEntryAdd(fields) }
        "timerecEntryUpdate" -> decodeKnownServerMessage { decodeTimerecEntryUpdate(fields) }
        "timerecEntryDelete" -> decodeKnownServerMessage { decodeTimerecEntryDelete(fields) }
        "eventAdd" -> decodeKnownServerMessage { decodeEventAdd(fields) }
        "eventUpdate" -> decodeKnownServerMessage { decodeEventUpdate(fields) }
        "eventDelete" -> decodeKnownServerMessage { decodeEventDelete(fields) }
        "initialSyncCompleted" -> decodeKnownServerMessage { decodeInitialSyncCompleted(fields) }
        "muxpkt" -> decodeKnownServerMessage { decodeMuxPacket(fields) }
        "queueStatus" -> decodeKnownServerMessage { decodeQueueStatus(fields) }
        "subscriptionStart" -> decodeKnownServerMessage { decodeSubscriptionStart(fields) }
        "subscriptionStop" -> decodeKnownServerMessage { decodeSubscriptionStop(fields) }
        "subscriptionGrace" -> decodeKnownServerMessage { decodeSubscriptionGrace(fields) }
        "subscriptionStatus" -> decodeKnownServerMessage { decodeSubscriptionStatus(fields) }
        "signalStatus" -> decodeKnownServerMessage { decodeSignalStatus(fields) }
        "descrambleInfo" -> decodeKnownServerMessage { decodeDescrambleInfo(fields) }
        "subscriptionSpeed" -> decodeKnownServerMessage { decodeSubscriptionSpeed(fields) }
        "timeshiftStatus" -> decodeKnownServerMessage { decodeTimeshiftStatus(fields) }
        "subscriptionSkip" -> decodeKnownServerMessage { decodeSubscriptionSkip(fields) }
        else -> HtspServerMessageUnknownMethod
    }
}

private fun decodeKnownServerMessage(block: () -> HtspServerMessage): HtspServerMessageDecodeResult =
    try {
        HtspServerMessageDecoded(block())
    } catch (_: IllegalArgumentException) {
        HtspServerMessageMalformedKnownMessage
    }

@JvmSynthetic
internal fun typedHtspServerMessageCatalogForTest(): List<Pair<String, String>> =
    typedHtspServerMessageCatalog.map { it.method to it.messageType }
