// Generated by docs/htsp-protocol/generate_typed_requests.py. DO NOT EDIT.
// docs/htsp-protocol/htsp_surface.py is the reviewed request/response constructor authority.
package at.bernhardberger.tvheadend.htsp.requests

import at.bernhardberger.tvheadend.htsp.connection.*

internal data class `TypedHtspRequestCatalogEntry-internal`(
    val method: String,
    val requestType: String,
    val responseType: String,
    val access: HtspAccess,
    val minimumProtocolVersion: Int?,
)

internal typealias TypedHtspRequestCatalogEntry =
    `TypedHtspRequestCatalogEntry-internal`

@get:JvmSynthetic
internal val typedHtspRequestCatalog: List<TypedHtspRequestCatalogEntry> = listOf(
    TypedHtspRequestCatalogEntry("getProfiles", "GetProfilesRequest", "GetProfilesResponse", HtspAccess.ACCESS_HTSP_STREAMING, 16),
    TypedHtspRequestCatalogEntry("getDiskSpace", "GetDiskSpaceRequest", "GetDiskSpaceResponse", HtspAccess.ACCESS_HTSP_STREAMING, 3),
    TypedHtspRequestCatalogEntry("getSysTime", "GetSysTimeRequest", "GetSysTimeResponse", HtspAccess.ACCESS_HTSP_STREAMING, 3),
    TypedHtspRequestCatalogEntry("enableAsyncMetadata", "EnableAsyncMetadataRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("getChannel", "GetChannelRequest", "GetChannelResponse", HtspAccess.ACCESS_HTSP_STREAMING, 14),
    TypedHtspRequestCatalogEntry("getEvent", "GetEventRequest", "GetEventResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("getEvents", "GetEventsRequest", "GetEventsResponse", HtspAccess.ACCESS_HTSP_STREAMING, 4),
    TypedHtspRequestCatalogEntry("epgQuery", "EpgQueryRequest", "EpgQueryResponse", HtspAccess.ACCESS_HTSP_STREAMING, 4),
    TypedHtspRequestCatalogEntry("getEpgObject", "GetEpgObjectRequest", "GetEpgObjectResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("getDvrConfigs", "GetDvrConfigsRequest", "GetDvrConfigsResponse", HtspAccess.ACCESS_HTSP_RECORDER, 16),
    TypedHtspRequestCatalogEntry("addDvrEntry", "AddDvrEntryRequest", "AddDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 4),
    TypedHtspRequestCatalogEntry("updateDvrEntry", "UpdateDvrEntryRequest", "UpdateDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 5),
    TypedHtspRequestCatalogEntry("stopDvrEntry", "StopDvrEntryRequest", "StopDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, null),
    TypedHtspRequestCatalogEntry("cancelDvrEntry", "CancelDvrEntryRequest", "CancelDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 5),
    TypedHtspRequestCatalogEntry("deleteDvrEntry", "DeleteDvrEntryRequest", "DeleteDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 4),
    TypedHtspRequestCatalogEntry("addAutorecEntry", "AddAutorecEntryRequest", "AddAutorecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 13),
    TypedHtspRequestCatalogEntry("updateAutorecEntry", "UpdateAutorecEntryRequest", "UpdateAutorecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 25),
    TypedHtspRequestCatalogEntry("deleteAutorecEntry", "DeleteAutorecEntryRequest", "DeleteAutorecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 13),
    TypedHtspRequestCatalogEntry("addTimerecEntry", "AddTimerecEntryRequest", "AddTimerecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 18),
    TypedHtspRequestCatalogEntry("updateTimerecEntry", "UpdateTimerecEntryRequest", "UpdateTimerecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 25),
    TypedHtspRequestCatalogEntry("deleteTimerecEntry", "DeleteTimerecEntryRequest", "DeleteTimerecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 18),
    TypedHtspRequestCatalogEntry("getDvrCutpoints", "GetDvrCutpointsRequest", "GetDvrCutpointsResponse", HtspAccess.ACCESS_HTSP_RECORDER, 12),
    TypedHtspRequestCatalogEntry("getTicket", "GetTicketRequest", "GetTicketResponse", HtspAccess.ACCESS_HTSP_STREAMING, 5),
    TypedHtspRequestCatalogEntry("subscribe", "SubscribeRequest", "SubscribeResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("unsubscribe", "UnsubscribeRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("subscriptionChangeWeight", "SubscriptionChangeWeightRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 5),
    TypedHtspRequestCatalogEntry("subscriptionSeek", "SubscriptionSeekRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionSkip", "SubscriptionSkipRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionSpeed", "SubscriptionSpeedRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionLive", "SubscriptionLiveRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionFilterStream", "SubscriptionFilterStreamRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 12),
    TypedHtspRequestCatalogEntry("fileOpen", "FileOpenRequest", "FileOpenResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    TypedHtspRequestCatalogEntry("fileRead", "FileReadRequest", "FileReadResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    TypedHtspRequestCatalogEntry("fileClose", "FileCloseRequest", "FileCloseResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    TypedHtspRequestCatalogEntry("fileStat", "FileStatRequest", "FileStatResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    TypedHtspRequestCatalogEntry("fileSeek", "FileSeekRequest", "FileSeekResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    TypedHtspRequestCatalogEntry("api", "ApiRequest", "ApiResponse", HtspAccess.ACCESS_ANONYMOUS, 24),
    TypedHtspRequestCatalogEntry("hello", "HelloRequest", "HelloResponse", HtspAccess.ACCESS_ANONYMOUS, null),
    TypedHtspRequestCatalogEntry("authenticate", "AuthenticateRequest", "AuthenticateResponse", HtspAccess.ACCESS_ANONYMOUS, null),
)

/** Fetches the server's stream-profile metadata through typed connection execution and returns its transport or reply failure as [HtspResult]. */
public suspend fun HtspConnection.getProfiles(
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetProfilesResponse> =
    execute(
        request = GetProfilesRequest(),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Reads free, used, and total recording-storage counters through the typed request boundary. */
public suspend fun HtspConnection.getDiskSpace(
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetDiskSpaceResponse> =
    execute(
        request = GetDiskSpaceRequest(),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Reads the server clock and timezone observations through typed connection execution. */
public suspend fun HtspConnection.getSysTime(
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetSysTimeResponse> =
    execute(
        request = GetSysTimeRequest(),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests asynchronous metadata delivery with the selected EPG window and language options and decodes the typed acknowledgement. */
public suspend fun HtspConnection.enableAsyncMetadata(
    epg: Long? = null,
    lastUpdate: Long? = null,
    epgMaxTime: Long? = null,
    language: String? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = EnableAsyncMetadataRequest(
            epg = epg,
            lastUpdate = lastUpdate,
            epgMaxTime = epgMaxTime,
            language = language,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Fetches one channel by unsigned identifier and decodes the reply through the typed connection boundary. */
public suspend fun HtspConnection.getChannel(
    channelId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetChannelResponse> =
    execute(
        request = GetChannelRequest(
            channelId = channelId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Fetches one EPG event by identifier, optionally localized to [language], through typed execution. */
public suspend fun HtspConnection.getEvent(
    eventId: Long,
    language: String? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetEventResponse> =
    execute(
        request = GetEventRequest(
            eventId = eventId,
            language = language,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Fetches an event window selected by channel, event, language, following count, or maximum time through typed execution. */
public suspend fun HtspConnection.getEvents(
    channelId: Long? = null,
    eventId: Long? = null,
    language: String? = null,
    numFollowing: Long? = null,
    maxTime: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetEventsResponse> =
    execute(
        request = GetEventsRequest(
            channelId = channelId,
            eventId = eventId,
            language = language,
            numFollowing = numFollowing,
            maxTime = maxTime,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Searches EPG text with the supplied channel, tag, content, language, detail, and duration filters through typed execution. */
public suspend fun HtspConnection.epgQuery(
    query: String,
    channelId: Long? = null,
    tagId: Long? = null,
    contentType: Long? = null,
    language: String? = null,
    fullText: Boolean? = null,
    mergeText: Boolean? = null,
    full: Long? = null,
    minDurationSeconds: Long? = null,
    maxDurationSeconds: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<EpgQueryResponse> =
    execute(
        request = EpgQueryRequest(
            query = query,
            channelId = channelId,
            tagId = tagId,
            contentType = contentType,
            language = language,
            fullText = fullText,
            mergeText = mergeText,
            full = full,
            minDurationSeconds = minDurationSeconds,
            maxDurationSeconds = maxDurationSeconds,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Fetches the selected detailed EPG object and decodes its finite broadcast shape through typed execution. */
public suspend fun HtspConnection.getEpgObject(
    id: Long,
    objectType: HtspEpgObjectType? = HtspEpgObjectType.BROADCAST,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetEpgObjectResponse> =
    execute(
        request = GetEpgObjectRequest(
            id = id,
            objectType = objectType,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Fetches visible DVR configurations through the typed recorder request boundary. */
public suspend fun HtspConnection.getDvrConfigs(
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetDvrConfigsResponse> =
    execute(
        request = GetDvrConfigsRequest(),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests DVR scheduling from the explicit selector and optional metadata, then decodes the typed mutation reply. */
public suspend fun HtspConnection.addDvrEntry(
    selector: AddDvrEntrySelector,
    configName: String? = null,
    language: String? = null,
    title: String? = null,
    subtitle: String? = null,
    summary: String? = null,
    description: String? = null,
    ageRating: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddDvrEntryResponse> =
    execute(
        request = AddDvrEntryRequest(
            selector = selector,
            configName = configName,
            language = language,
            title = title,
            subtitle = subtitle,
            summary = summary,
            description = description,
            ageRating = ageRating,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Adapts [eventId] to [AddDvrEntrySelector.Event] before sending the same typed DVR-add request. */
public suspend fun HtspConnection.addDvrEntry(
    eventId: Long,
    configName: String? = null,
    language: String? = null,
    title: String? = null,
    subtitle: String? = null,
    summary: String? = null,
    description: String? = null,
    ageRating: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddDvrEntryResponse> =
    execute(
        request = AddDvrEntryRequest(
            selector = AddDvrEntrySelector.Event(eventId),
            configName = configName,
            language = language,
            title = title,
            subtitle = subtitle,
            summary = summary,
            description = description,
            ageRating = ageRating,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Adapts channel, start, and stop to [AddDvrEntrySelector.ExplicitChannelTime] before sending a typed DVR-add request. */
public suspend fun HtspConnection.addDvrEntry(
    channelId: Long,
    start: Long,
    stop: Long,
    configName: String? = null,
    language: String? = null,
    title: String? = null,
    subtitle: String? = null,
    summary: String? = null,
    description: String? = null,
    ageRating: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddDvrEntryResponse> =
    execute(
        request = AddDvrEntryRequest(
            selector = AddDvrEntrySelector.ExplicitChannelTime(channelId, start, stop),
            configName = configName,
            language = language,
            title = title,
            subtitle = subtitle,
            summary = summary,
            description = description,
            ageRating = ageRating,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a DVR-entry change carrying the supplied partial metadata, timing, progress, and policy fields. */
public suspend fun HtspConnection.updateDvrEntry(
    entryId: Long,
    channelId: Long? = null,
    configName: String? = null,
    title: String? = null,
    subtitle: String? = null,
    summary: String? = null,
    description: String? = null,
    language: String? = null,
    comment: String? = null,
    playCount: Long? = null,
    playPosition: Long? = null,
    enabled: Long? = null,
    start: Long? = null,
    stop: Long? = null,
    startExtra: Long? = null,
    stopExtra: Long? = null,
    retention: Long? = null,
    removal: Long? = null,
    priority: Long? = null,
    ageRating: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<UpdateDvrEntryResponse> =
    execute(
        request = UpdateDvrEntryRequest(
            entryId = entryId,
            channelId = channelId,
            configName = configName,
            title = title,
            subtitle = subtitle,
            summary = summary,
            description = description,
            language = language,
            comment = comment,
            playCount = playCount,
            playPosition = playPosition,
            enabled = enabled,
            start = start,
            stop = stop,
            startExtra = startExtra,
            stopExtra = stopExtra,
            retention = retention,
            removal = removal,
            priority = priority,
            ageRating = ageRating,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests that the selected DVR entry stop and decodes the server's typed mutation reply. */
public suspend fun HtspConnection.stopDvrEntry(
    entryId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<StopDvrEntryResponse> =
    execute(
        request = StopDvrEntryRequest(
            entryId = entryId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests cancellation of the selected DVR entry and decodes the server's typed mutation reply. */
public suspend fun HtspConnection.cancelDvrEntry(
    entryId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<CancelDvrEntryResponse> =
    execute(
        request = CancelDvrEntryRequest(
            entryId = entryId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests deletion of the selected DVR entry and returns the decoded typed mutation reply. */
public suspend fun HtspConnection.deleteDvrEntry(
    entryId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<DeleteDvrEntryResponse> =
    execute(
        request = DeleteDvrEntryRequest(
            entryId = entryId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests an automatic recording rule with the supplied title, matching, schedule, retention, and ownership fields. */
public suspend fun HtspConnection.addAutorecEntry(
    title: String,
    channel: HtspRecordingRuleChannel? = null,
    minDurationSeconds: Long? = null,
    maxDurationSeconds: Long? = null,
    fullText: Long? = null,
    mergeText: Long? = null,
    duplicateDetection: Long? = null,
    maximumRecordingCount: Long? = null,
    broadcastType: Long? = null,
    startExtraMinutes: Long? = null,
    stopExtraMinutes: Long? = null,
    seriesLinkUri: String? = null,
    approximateStartMinutesSinceMidnight: Int? = null,
    startMinutesSinceMidnight: Int? = null,
    startWindowEndMinutesSinceMidnight: Int? = null,
    enabled: Boolean? = null,
    retentionDays: Long? = null,
    removalDays: Long? = null,
    priority: Long? = null,
    name: String? = null,
    comment: String? = null,
    directory: String? = null,
    configName: String? = null,
    daysOfWeekMask: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddAutorecEntryResponse> =
    execute(
        request = AddAutorecEntryRequest(
            title = title,
            channel = channel,
            minDurationSeconds = minDurationSeconds,
            maxDurationSeconds = maxDurationSeconds,
            fullText = fullText,
            mergeText = mergeText,
            duplicateDetection = duplicateDetection,
            maximumRecordingCount = maximumRecordingCount,
            broadcastType = broadcastType,
            startExtraMinutes = startExtraMinutes,
            stopExtraMinutes = stopExtraMinutes,
            seriesLinkUri = seriesLinkUri,
            approximateStartMinutesSinceMidnight = approximateStartMinutesSinceMidnight,
            startMinutesSinceMidnight = startMinutesSinceMidnight,
            startWindowEndMinutesSinceMidnight = startWindowEndMinutesSinceMidnight,
            enabled = enabled,
            retentionDays = retentionDays,
            removalDays = removalDays,
            priority = priority,
            name = name,
            comment = comment,
            directory = directory,
            configName = configName,
            daysOfWeekMask = daysOfWeekMask,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a change to the identified automatic recording rule using only the supplied selector and policy fields. */
public suspend fun HtspConnection.updateAutorecEntry(
    id: String,
    channel: HtspRecordingRuleChannel? = null,
    minDurationSeconds: Long? = null,
    maxDurationSeconds: Long? = null,
    fullText: Long? = null,
    mergeText: Long? = null,
    duplicateDetection: Long? = null,
    maximumRecordingCount: Long? = null,
    broadcastType: Long? = null,
    startExtraMinutes: Long? = null,
    stopExtraMinutes: Long? = null,
    seriesLinkUri: String? = null,
    startMinutesSinceMidnight: Int? = null,
    startWindowEndMinutesSinceMidnight: Int? = null,
    enabled: Boolean? = null,
    retentionDays: Long? = null,
    removalDays: Long? = null,
    priority: Long? = null,
    name: String? = null,
    comment: String? = null,
    directory: String? = null,
    title: String? = null,
    configName: String? = null,
    daysOfWeekMask: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<UpdateAutorecEntryResponse> =
    execute(
        request = UpdateAutorecEntryRequest(
            id = id,
            channel = channel,
            minDurationSeconds = minDurationSeconds,
            maxDurationSeconds = maxDurationSeconds,
            fullText = fullText,
            mergeText = mergeText,
            duplicateDetection = duplicateDetection,
            maximumRecordingCount = maximumRecordingCount,
            broadcastType = broadcastType,
            startExtraMinutes = startExtraMinutes,
            stopExtraMinutes = stopExtraMinutes,
            seriesLinkUri = seriesLinkUri,
            startMinutesSinceMidnight = startMinutesSinceMidnight,
            startWindowEndMinutesSinceMidnight = startWindowEndMinutesSinceMidnight,
            enabled = enabled,
            retentionDays = retentionDays,
            removalDays = removalDays,
            priority = priority,
            name = name,
            comment = comment,
            directory = directory,
            title = title,
            configName = configName,
            daysOfWeekMask = daysOfWeekMask,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests deletion of the automatic recording rule identified by [id] through the typed recorder boundary. */
public suspend fun HtspConnection.deleteAutorecEntry(
    id: String,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<DeleteAutorecEntryResponse> =
    execute(
        request = DeleteAutorecEntryRequest(
            id = id,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a time-based recording rule with the supplied channel, daily interval, day mask, and policy fields. */
public suspend fun HtspConnection.addTimerecEntry(
    title: String,
    channel: HtspRecordingRuleChannel? = null,
    startMinutesSinceMidnight: Long? = null,
    stopMinutesSinceMidnight: Long? = null,
    enabled: Boolean? = null,
    retentionDays: Long? = null,
    removalDays: Long? = null,
    priority: Long? = null,
    name: String? = null,
    comment: String? = null,
    directory: String? = null,
    configName: String? = null,
    daysOfWeekMask: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddTimerecEntryResponse> =
    execute(
        request = AddTimerecEntryRequest(
            title = title,
            channel = channel,
            startMinutesSinceMidnight = startMinutesSinceMidnight,
            stopMinutesSinceMidnight = stopMinutesSinceMidnight,
            enabled = enabled,
            retentionDays = retentionDays,
            removalDays = removalDays,
            priority = priority,
            name = name,
            comment = comment,
            directory = directory,
            configName = configName,
            daysOfWeekMask = daysOfWeekMask,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a change to the identified time-based recording rule with the supplied interval and policy fields. */
public suspend fun HtspConnection.updateTimerecEntry(
    id: String,
    channel: HtspRecordingRuleChannel? = null,
    startMinutesSinceMidnight: Long? = null,
    stopMinutesSinceMidnight: Long? = null,
    enabled: Boolean? = null,
    retentionDays: Long? = null,
    removalDays: Long? = null,
    priority: Long? = null,
    name: String? = null,
    comment: String? = null,
    directory: String? = null,
    title: String? = null,
    configName: String? = null,
    daysOfWeekMask: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<UpdateTimerecEntryResponse> =
    execute(
        request = UpdateTimerecEntryRequest(
            id = id,
            channel = channel,
            startMinutesSinceMidnight = startMinutesSinceMidnight,
            stopMinutesSinceMidnight = stopMinutesSinceMidnight,
            enabled = enabled,
            retentionDays = retentionDays,
            removalDays = removalDays,
            priority = priority,
            name = name,
            comment = comment,
            directory = directory,
            title = title,
            configName = configName,
            daysOfWeekMask = daysOfWeekMask,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests deletion of the time-based recording rule identified by [id] through typed connection execution. */
public suspend fun HtspConnection.deleteTimerecEntry(
    id: String,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<DeleteTimerecEntryResponse> =
    execute(
        request = DeleteTimerecEntryRequest(
            id = id,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Fetches the ordered cutpoint coordinates and action codes for one DVR entry through typed execution. */
public suspend fun HtspConnection.getDvrCutpoints(
    entryId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetDvrCutpointsResponse> =
    execute(
        request = GetDvrCutpointsRequest(
            entryId = entryId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a temporary access path and ticket for exactly one channel or DVR selector through typed execution. */
public suspend fun HtspConnection.getTicket(
    selector: GetTicketSelector,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetTicketResponse> =
    execute(
        request = GetTicketRequest(
            selector = selector,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Forwards a channel ticket selector without widening it to another source kind, preserving the typed result boundary. */
public suspend fun HtspConnection.getTicket(
    selector: GetTicketSelector.Channel,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetTicketResponse> =
    execute(
        request = GetTicketRequest(
            selector = selector,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Forwards a DVR ticket selector without widening it to another source kind, preserving the typed result boundary. */
public suspend fun HtspConnection.getTicket(
    selector: GetTicketSelector.Dvr,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetTicketResponse> =
    execute(
        request = GetTicketRequest(
            selector = selector,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a subscription for exactly one channel selector with profile, weight, timestamp, timeshift, and queue options. */
public suspend fun HtspConnection.subscribe(
    subscriptionId: Long,
    channel: SubscribeChannel,
    profile: String? = null,
    weight: Long? = null,
    ninetyKhz: Long? = null,
    timeshiftPeriodSeconds: Long? = null,
    queueDepth: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<SubscribeResponse> =
    execute(
        request = SubscribeRequest(
            subscriptionId = subscriptionId,
            channel = channel,
            profile = profile,
            weight = weight,
            ninetyKhz = ninetyKhz,
            timeshiftPeriodSeconds = timeshiftPeriodSeconds,
            queueDepth = queueDepth,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Wraps [channelId] as [SubscribeChannel.Id] before sending the typed subscription request. */
public suspend fun HtspConnection.subscribe(
    subscriptionId: Long,
    channelId: Long,
    profile: String? = null,
    weight: Long? = null,
    ninetyKhz: Long? = null,
    timeshiftPeriodSeconds: Long? = null,
    queueDepth: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<SubscribeResponse> =
    execute(
        request = SubscribeRequest(
            subscriptionId = subscriptionId,
            channel = SubscribeChannel.Id(channelId),
            profile = profile,
            weight = weight,
            ninetyKhz = ninetyKhz,
            timeshiftPeriodSeconds = timeshiftPeriodSeconds,
            queueDepth = queueDepth,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Wraps [channelName] as [SubscribeChannel.Name] before sending the typed subscription request. */
public suspend fun HtspConnection.subscribe(
    subscriptionId: Long,
    channelName: String,
    profile: String? = null,
    weight: Long? = null,
    ninetyKhz: Long? = null,
    timeshiftPeriodSeconds: Long? = null,
    queueDepth: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<SubscribeResponse> =
    execute(
        request = SubscribeRequest(
            subscriptionId = subscriptionId,
            channel = SubscribeChannel.Name(channelName),
            profile = profile,
            weight = weight,
            ninetyKhz = ninetyKhz,
            timeshiftPeriodSeconds = timeshiftPeriodSeconds,
            queueDepth = queueDepth,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests termination of the selected subscription and decodes the typed acknowledgement. */
public suspend fun HtspConnection.unsubscribe(
    subscriptionId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = UnsubscribeRequest(
            subscriptionId = subscriptionId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a scheduling-weight change for one subscription and decodes its typed acknowledgement; the reply does not establish that the weight was applied. */
public suspend fun HtspConnection.subscriptionChangeWeight(
    subscriptionId: Long,
    weight: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionChangeWeightRequest(
            subscriptionId = subscriptionId,
            weight = weight,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a subscription seek by exactly one signed time or byte coordinate and decodes the typed acknowledgement. */
public suspend fun HtspConnection.subscriptionSeek(
    subscriptionId: Long,
    position: SubscriptionSeekPosition,
    absolute: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionSeekRequest(
            subscriptionId = subscriptionId,
            position = position,
            absolute = absolute,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Keeps a time seek selector distinct while forwarding it through the typed subscription-seek boundary. */
public suspend fun HtspConnection.subscriptionSeek(
    subscriptionId: Long,
    position: SubscriptionSeekPosition.Time,
    absolute: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionSeekRequest(
            subscriptionId = subscriptionId,
            position = position,
            absolute = absolute,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Keeps a byte-size seek selector distinct while forwarding it through the typed subscription-seek boundary. */
public suspend fun HtspConnection.subscriptionSeek(
    subscriptionId: Long,
    position: SubscriptionSeekPosition.Size,
    absolute: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionSeekRequest(
            subscriptionId = subscriptionId,
            position = position,
            absolute = absolute,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a subscription skip using exactly one signed time or byte coordinate and decodes the typed acknowledgement. */
public suspend fun HtspConnection.subscriptionSkip(
    subscriptionId: Long,
    position: SubscriptionSeekPosition,
    absolute: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionSkipRequest(
            subscriptionId = subscriptionId,
            position = position,
            absolute = absolute,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Adapts the concrete time coordinate to the shared skip request without changing typed failure handling. */
public suspend fun HtspConnection.subscriptionSkip(
    subscriptionId: Long,
    position: SubscriptionSeekPosition.Time,
    absolute: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionSkipRequest(
            subscriptionId = subscriptionId,
            position = position,
            absolute = absolute,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Adapts the concrete byte coordinate to the shared skip request without changing typed failure handling. */
public suspend fun HtspConnection.subscriptionSkip(
    subscriptionId: Long,
    position: SubscriptionSeekPosition.Size,
    absolute: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionSkipRequest(
            subscriptionId = subscriptionId,
            position = position,
            absolute = absolute,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests the signed playback speed for one subscription and decodes the typed acknowledgement. */
public suspend fun HtspConnection.subscriptionSpeed(
    subscriptionId: Long,
    speed: Int,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionSpeedRequest(
            subscriptionId = subscriptionId,
            speed = speed,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests live mode for one subscription and decodes the typed acknowledgement; asynchronous subscription status remains authoritative for the resulting position. */
public suspend fun HtspConnection.subscriptionLive(
    subscriptionId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionLiveRequest(
            subscriptionId = subscriptionId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests the supplied immutable enable and disable stream-index filters and decodes the typed acknowledgement. */
public suspend fun HtspConnection.subscriptionFilterStream(
    subscriptionId: Long,
    enable: List<Long>? = null,
    disable: List<Long>? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    execute(
        request = SubscriptionFilterStreamRequest(
            subscriptionId = subscriptionId,
            enable = enable,
            disable = disable,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests opening the exact supplied protocol file selector and decodes the returned handle; no path normalization is added. */
public suspend fun HtspConnection.fileOpen(
    file: String,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileOpenResponse> =
    execute(
        request = FileOpenRequest(
            file = file,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Reads a bounded byte range from an open protocol file handle through typed execution. */
public suspend fun HtspConnection.fileRead(
    id: Long,
    size: Long,
    offset: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileReadResponse> =
    execute(
        request = FileReadRequest(
            id = id,
            size = size,
            offset = offset,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests closure of an open protocol file handle without recording-progress fields and decodes the acknowledgement. */
public suspend fun HtspConnection.fileClose(
    id: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileCloseResponse> =
    execute(
        request = FileCloseRequest(
            id = id,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Projects all close parameters so requested recording position and play count can be sent with typed failure handling. */
public suspend fun HtspConnection.fileCloseWithProgress(
    id: Long,
    playPositionSeconds: Long?,
    playCount: Long?,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileCloseResponse> =
    execute(
        request = FileCloseRequest(
            id = id,
            playPositionSeconds = playPositionSeconds,
            playCount = playCount,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Reads size and modification metadata for an open protocol file handle through typed execution. */
public suspend fun HtspConnection.fileStat(
    id: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileStatResponse> =
    execute(
        request = FileStatRequest(
            id = id,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests a signed seek from the optional origin and decodes the server-reported absolute file offset. */
public suspend fun HtspConnection.fileSeek(
    id: Long,
    offset: Long,
    whence: FileSeekWhence? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileSeekResponse> =
    execute(
        request = FileSeekRequest(
            id = id,
            offset = offset,
            whence = whence,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Negotiates the requested HTSP version and client name through the typed handshake request boundary. */
public suspend fun HtspConnection.hello(
    htspVersion: Long,
    clientName: String,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HelloResponse> =
    execute(
        request = HelloRequest(
            htspVersion = htspVersion,
            clientName = clientName,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

/** Requests the current connection's authentication and access observations through typed execution; credentials stay in the envelope. */
public suspend fun HtspConnection.authenticate(
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AuthenticateResponse> =
    execute(
        request = AuthenticateRequest(),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )
