package at.bernhardberger.tvheadend.htsp

import at.bernhardberger.tvheadend.htsp.requests.HtspAccess

internal data class HtspRequestInventoryEntry(
    val method: String,
    val access: HtspAccess,
    val minimumProtocolVersion: Int?,
)

internal val typedHtspRequestCatalog = listOf(
    HtspRequestInventoryEntry("getProfiles", HtspAccess.ACCESS_HTSP_STREAMING, 16),
    HtspRequestInventoryEntry("getDiskSpace", HtspAccess.ACCESS_HTSP_STREAMING, 3),
    HtspRequestInventoryEntry("getSysTime", HtspAccess.ACCESS_HTSP_STREAMING, 3),
    HtspRequestInventoryEntry("enableAsyncMetadata", HtspAccess.ACCESS_HTSP_STREAMING, null),
    HtspRequestInventoryEntry("getChannel", HtspAccess.ACCESS_HTSP_STREAMING, 14),
    HtspRequestInventoryEntry("getEvent", HtspAccess.ACCESS_HTSP_STREAMING, null),
    HtspRequestInventoryEntry("getEvents", HtspAccess.ACCESS_HTSP_STREAMING, 4),
    HtspRequestInventoryEntry("epgQuery", HtspAccess.ACCESS_HTSP_STREAMING, 4),
    HtspRequestInventoryEntry("getEpgObject", HtspAccess.ACCESS_HTSP_STREAMING, null),
    HtspRequestInventoryEntry("getDvrConfigs", HtspAccess.ACCESS_HTSP_RECORDER, 16),
    HtspRequestInventoryEntry("addDvrEntry", HtspAccess.ACCESS_HTSP_RECORDER, 4),
    HtspRequestInventoryEntry("updateDvrEntry", HtspAccess.ACCESS_HTSP_RECORDER, 5),
    HtspRequestInventoryEntry("stopDvrEntry", HtspAccess.ACCESS_HTSP_RECORDER, null),
    HtspRequestInventoryEntry("cancelDvrEntry", HtspAccess.ACCESS_HTSP_RECORDER, 5),
    HtspRequestInventoryEntry("deleteDvrEntry", HtspAccess.ACCESS_HTSP_RECORDER, 4),
    HtspRequestInventoryEntry("addAutorecEntry", HtspAccess.ACCESS_HTSP_RECORDER, 13),
    HtspRequestInventoryEntry("updateAutorecEntry", HtspAccess.ACCESS_HTSP_RECORDER, 25),
    HtspRequestInventoryEntry("deleteAutorecEntry", HtspAccess.ACCESS_HTSP_RECORDER, 13),
    HtspRequestInventoryEntry("addTimerecEntry", HtspAccess.ACCESS_HTSP_RECORDER, 18),
    HtspRequestInventoryEntry("updateTimerecEntry", HtspAccess.ACCESS_HTSP_RECORDER, 25),
    HtspRequestInventoryEntry("deleteTimerecEntry", HtspAccess.ACCESS_HTSP_RECORDER, 18),
    HtspRequestInventoryEntry("getDvrCutpoints", HtspAccess.ACCESS_HTSP_RECORDER, 12),
    HtspRequestInventoryEntry("getTicket", HtspAccess.ACCESS_HTSP_STREAMING, 5),
    HtspRequestInventoryEntry("subscribe", HtspAccess.ACCESS_HTSP_STREAMING, null),
    HtspRequestInventoryEntry("unsubscribe", HtspAccess.ACCESS_HTSP_STREAMING, null),
    HtspRequestInventoryEntry("subscriptionChangeWeight", HtspAccess.ACCESS_HTSP_STREAMING, 5),
    HtspRequestInventoryEntry("subscriptionSeek", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    HtspRequestInventoryEntry("subscriptionSkip", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    HtspRequestInventoryEntry("subscriptionSpeed", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    HtspRequestInventoryEntry("subscriptionLive", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    HtspRequestInventoryEntry("subscriptionFilterStream", HtspAccess.ACCESS_HTSP_STREAMING, 12),
    HtspRequestInventoryEntry("fileOpen", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    HtspRequestInventoryEntry("fileRead", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    HtspRequestInventoryEntry("fileClose", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    HtspRequestInventoryEntry("fileStat", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    HtspRequestInventoryEntry("fileSeek", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    HtspRequestInventoryEntry("api", HtspAccess.ACCESS_ANONYMOUS, 24),
    HtspRequestInventoryEntry("hello", HtspAccess.ACCESS_ANONYMOUS, null),
    HtspRequestInventoryEntry("authenticate", HtspAccess.ACCESS_ANONYMOUS, null),
)

internal data class HtspServerMessageInventoryEntry(
    val method: String,
    val messageType: String,
)

internal val typedHtspServerMessageInventory = listOf(
    HtspServerMessageInventoryEntry("channelAdd", "HtspChannelAddMessage"),
    HtspServerMessageInventoryEntry("channelUpdate", "HtspChannelUpdateMessage"),
    HtspServerMessageInventoryEntry("channelDelete", "HtspChannelDeleteMessage"),
    HtspServerMessageInventoryEntry("tagAdd", "HtspTagAddMessage"),
    HtspServerMessageInventoryEntry("tagUpdate", "HtspTagUpdateMessage"),
    HtspServerMessageInventoryEntry("tagDelete", "HtspTagDeleteMessage"),
    HtspServerMessageInventoryEntry("dvrEntryAdd", "HtspDvrEntryAddMessage"),
    HtspServerMessageInventoryEntry("dvrEntryUpdate", "HtspDvrEntryUpdateMessage"),
    HtspServerMessageInventoryEntry("dvrEntryDelete", "HtspDvrEntryDeleteMessage"),
    HtspServerMessageInventoryEntry("autorecEntryAdd", "HtspAutorecEntryAddMessage"),
    HtspServerMessageInventoryEntry("autorecEntryUpdate", "HtspAutorecEntryUpdateMessage"),
    HtspServerMessageInventoryEntry("autorecEntryDelete", "HtspAutorecEntryDeleteMessage"),
    HtspServerMessageInventoryEntry("timerecEntryAdd", "HtspTimerecEntryAddMessage"),
    HtspServerMessageInventoryEntry("timerecEntryUpdate", "HtspTimerecEntryUpdateMessage"),
    HtspServerMessageInventoryEntry("timerecEntryDelete", "HtspTimerecEntryDeleteMessage"),
    HtspServerMessageInventoryEntry("eventAdd", "HtspEventAddMessage"),
    HtspServerMessageInventoryEntry("eventUpdate", "HtspEventUpdateMessage"),
    HtspServerMessageInventoryEntry("eventDelete", "HtspEventDeleteMessage"),
    HtspServerMessageInventoryEntry("initialSyncCompleted", "HtspInitialSyncCompletedMessage"),
    HtspServerMessageInventoryEntry("muxpkt", "HtspMuxPacketMessage"),
    HtspServerMessageInventoryEntry("queueStatus", "HtspQueueStatusMessage"),
    HtspServerMessageInventoryEntry("subscriptionStart", "HtspSubscriptionStartMessage"),
    HtspServerMessageInventoryEntry("subscriptionStop", "HtspSubscriptionStopMessage"),
    HtspServerMessageInventoryEntry("subscriptionGrace", "HtspSubscriptionGraceMessage"),
    HtspServerMessageInventoryEntry("subscriptionStatus", "HtspSubscriptionStatusMessage"),
    HtspServerMessageInventoryEntry("signalStatus", "HtspSignalStatusMessage"),
    HtspServerMessageInventoryEntry("descrambleInfo", "HtspDescrambleInfoMessage"),
    HtspServerMessageInventoryEntry("subscriptionSpeed", "HtspSubscriptionSpeedMessage"),
    HtspServerMessageInventoryEntry("timeshiftStatus", "HtspTimeshiftStatusMessage"),
    HtspServerMessageInventoryEntry("subscriptionSkip", "HtspSubscriptionSkipMessage"),
)
