// Generated by docs/htsp-protocol/generate_typed_requests.py. DO NOT EDIT.
// The reviewed catalog in that generator is the request/response constructor authority.
package at.bernhardberger.tvheadend.htsp

internal data class `TypedHtspRequestCatalogEntry-internal`(
    val method: String,
    val requestType: String,
    val responseType: String,
    val access: HtspAccess,
    val minimumProtocolVersion: Int?,
)

internal typealias TypedHtspRequestCatalogEntry =
    `TypedHtspRequestCatalogEntry-internal`

@get:JvmSynthetic
internal val typedHtspRequestCatalog: List<TypedHtspRequestCatalogEntry> = listOf(
    TypedHtspRequestCatalogEntry("getProfiles", "GetProfilesRequest", "GetProfilesResponse", HtspAccess.ACCESS_HTSP_STREAMING, 16),
    TypedHtspRequestCatalogEntry("getDiskSpace", "GetDiskSpaceRequest", "GetDiskSpaceResponse", HtspAccess.ACCESS_HTSP_STREAMING, 3),
    TypedHtspRequestCatalogEntry("getSysTime", "GetSysTimeRequest", "GetSysTimeResponse", HtspAccess.ACCESS_HTSP_STREAMING, 3),
    TypedHtspRequestCatalogEntry("getChannel", "GetChannelRequest", "GetChannelResponse", HtspAccess.ACCESS_HTSP_STREAMING, 14),
    TypedHtspRequestCatalogEntry("getEvent", "GetEventRequest", "GetEventResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("getEvents", "GetEventsRequest", "GetEventsResponse", HtspAccess.ACCESS_HTSP_STREAMING, 4),
    TypedHtspRequestCatalogEntry("getDvrConfigs", "GetDvrConfigsRequest", "GetDvrConfigsResponse", HtspAccess.ACCESS_HTSP_RECORDER, 16),
    TypedHtspRequestCatalogEntry("addDvrEntry", "AddDvrEntryRequest", "AddDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 4),
    TypedHtspRequestCatalogEntry("updateDvrEntry", "UpdateDvrEntryRequest", "UpdateDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 5),
    TypedHtspRequestCatalogEntry("stopDvrEntry", "StopDvrEntryRequest", "StopDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, null),
    TypedHtspRequestCatalogEntry("cancelDvrEntry", "CancelDvrEntryRequest", "CancelDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 5),
    TypedHtspRequestCatalogEntry("deleteDvrEntry", "DeleteDvrEntryRequest", "DeleteDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 4),
    TypedHtspRequestCatalogEntry("getDvrCutpoints", "GetDvrCutpointsRequest", "GetDvrCutpointsResponse", HtspAccess.ACCESS_HTSP_RECORDER, 12),
    TypedHtspRequestCatalogEntry("subscribe", "SubscribeRequest", "SubscribeResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("unsubscribe", "UnsubscribeRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("subscriptionChangeWeight", "SubscriptionChangeWeightRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 5),
    TypedHtspRequestCatalogEntry("subscriptionSeek", "SubscriptionSeekRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionSpeed", "SubscriptionSpeedRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionLive", "SubscriptionLiveRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionFilterStream", "SubscriptionFilterStreamRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 12),
)

public suspend fun HtspConnection.getProfiles(request: GetProfilesRequest = GetProfilesRequest()): HtspResult<GetProfilesResponse> = call(request)
public suspend fun HtspConnection.getDiskSpace(request: GetDiskSpaceRequest = GetDiskSpaceRequest()): HtspResult<GetDiskSpaceResponse> = call(request)
public suspend fun HtspConnection.getSysTime(request: GetSysTimeRequest = GetSysTimeRequest()): HtspResult<GetSysTimeResponse> = call(request)
public suspend fun HtspConnection.getChannel(request: GetChannelRequest): HtspResult<GetChannelResponse> = call(request)
public suspend fun HtspConnection.getEvent(request: GetEventRequest): HtspResult<GetEventResponse> = call(request)
public suspend fun HtspConnection.getEvents(request: GetEventsRequest): HtspResult<GetEventsResponse> = call(request)
public suspend fun HtspConnection.getDvrConfigs(request: GetDvrConfigsRequest = GetDvrConfigsRequest()): HtspResult<GetDvrConfigsResponse> = call(request)
public suspend fun HtspConnection.addDvrEntry(request: AddDvrEntryRequest): HtspResult<AddDvrEntryResponse> = call(request)
public suspend fun HtspConnection.updateDvrEntry(request: UpdateDvrEntryRequest): HtspResult<UpdateDvrEntryResponse> = call(request)
public suspend fun HtspConnection.stopDvrEntry(request: StopDvrEntryRequest): HtspResult<StopDvrEntryResponse> = call(request)
public suspend fun HtspConnection.cancelDvrEntry(request: CancelDvrEntryRequest): HtspResult<CancelDvrEntryResponse> = call(request)
public suspend fun HtspConnection.deleteDvrEntry(request: DeleteDvrEntryRequest): HtspResult<DeleteDvrEntryResponse> = call(request)
public suspend fun HtspConnection.getDvrCutpoints(request: GetDvrCutpointsRequest): HtspResult<GetDvrCutpointsResponse> = call(request)
public suspend fun HtspConnection.subscribe(request: SubscribeRequest): HtspResult<SubscribeResponse> = call(request)
public suspend fun HtspConnection.unsubscribe(request: UnsubscribeRequest): HtspResult<HtspEmptyResponse> = call(request)
public suspend fun HtspConnection.subscriptionChangeWeight(request: SubscriptionChangeWeightRequest): HtspResult<HtspEmptyResponse> = call(request)
public suspend fun HtspConnection.subscriptionSeek(request: SubscriptionSeekRequest): HtspResult<HtspEmptyResponse> = call(request)
public suspend fun HtspConnection.subscriptionSpeed(request: SubscriptionSpeedRequest): HtspResult<HtspEmptyResponse> = call(request)
public suspend fun HtspConnection.subscriptionLive(request: SubscriptionLiveRequest): HtspResult<HtspEmptyResponse> = call(request)
public suspend fun HtspConnection.subscriptionFilterStream(request: SubscriptionFilterStreamRequest): HtspResult<HtspEmptyResponse> = call(request)
