// Generated by docs/htsp-protocol/generate_typed_requests.py. DO NOT EDIT.
// The reviewed catalog in that generator is the request/response constructor authority.
package at.bernhardberger.tvheadend.htsp

internal data class `TypedHtspRequestCatalogEntry-internal`(
    val method: String,
    val requestType: String,
    val responseType: String,
    val access: HtspAccess,
    val minimumProtocolVersion: Int?,
)

internal typealias TypedHtspRequestCatalogEntry =
    `TypedHtspRequestCatalogEntry-internal`

@get:JvmSynthetic
internal val typedHtspRequestCatalog: List<TypedHtspRequestCatalogEntry> = listOf(
    TypedHtspRequestCatalogEntry("getProfiles", "GetProfilesRequest", "GetProfilesResponse", HtspAccess.ACCESS_HTSP_STREAMING, 16),
    TypedHtspRequestCatalogEntry("getDiskSpace", "GetDiskSpaceRequest", "GetDiskSpaceResponse", HtspAccess.ACCESS_HTSP_STREAMING, 3),
    TypedHtspRequestCatalogEntry("getSysTime", "GetSysTimeRequest", "GetSysTimeResponse", HtspAccess.ACCESS_HTSP_STREAMING, 3),
    TypedHtspRequestCatalogEntry("enableAsyncMetadata", "EnableAsyncMetadataRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("getChannel", "GetChannelRequest", "GetChannelResponse", HtspAccess.ACCESS_HTSP_STREAMING, 14),
    TypedHtspRequestCatalogEntry("getEvent", "GetEventRequest", "GetEventResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("getEvents", "GetEventsRequest", "GetEventsResponse", HtspAccess.ACCESS_HTSP_STREAMING, 4),
    TypedHtspRequestCatalogEntry("epgQuery", "EpgQueryRequest", "EpgQueryResponse", HtspAccess.ACCESS_HTSP_STREAMING, 4),
    TypedHtspRequestCatalogEntry("getEpgObject", "GetEpgObjectRequest", "GetEpgObjectResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("getDvrConfigs", "GetDvrConfigsRequest", "GetDvrConfigsResponse", HtspAccess.ACCESS_HTSP_RECORDER, 16),
    TypedHtspRequestCatalogEntry("addDvrEntry", "AddDvrEntryRequest", "AddDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 4),
    TypedHtspRequestCatalogEntry("updateDvrEntry", "UpdateDvrEntryRequest", "UpdateDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 5),
    TypedHtspRequestCatalogEntry("stopDvrEntry", "StopDvrEntryRequest", "StopDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, null),
    TypedHtspRequestCatalogEntry("cancelDvrEntry", "CancelDvrEntryRequest", "CancelDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 5),
    TypedHtspRequestCatalogEntry("deleteDvrEntry", "DeleteDvrEntryRequest", "DeleteDvrEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 4),
    TypedHtspRequestCatalogEntry("addAutorecEntry", "AddAutorecEntryRequest", "AddAutorecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 13),
    TypedHtspRequestCatalogEntry("updateAutorecEntry", "UpdateAutorecEntryRequest", "UpdateAutorecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 25),
    TypedHtspRequestCatalogEntry("deleteAutorecEntry", "DeleteAutorecEntryRequest", "DeleteAutorecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 13),
    TypedHtspRequestCatalogEntry("addTimerecEntry", "AddTimerecEntryRequest", "AddTimerecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 18),
    TypedHtspRequestCatalogEntry("updateTimerecEntry", "UpdateTimerecEntryRequest", "UpdateTimerecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 25),
    TypedHtspRequestCatalogEntry("deleteTimerecEntry", "DeleteTimerecEntryRequest", "DeleteTimerecEntryResponse", HtspAccess.ACCESS_HTSP_RECORDER, 18),
    TypedHtspRequestCatalogEntry("getDvrCutpoints", "GetDvrCutpointsRequest", "GetDvrCutpointsResponse", HtspAccess.ACCESS_HTSP_RECORDER, 12),
    TypedHtspRequestCatalogEntry("getTicket", "GetTicketRequest", "GetTicketResponse", HtspAccess.ACCESS_HTSP_STREAMING, 5),
    TypedHtspRequestCatalogEntry("subscribe", "SubscribeRequest", "SubscribeResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("unsubscribe", "UnsubscribeRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, null),
    TypedHtspRequestCatalogEntry("subscriptionChangeWeight", "SubscriptionChangeWeightRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 5),
    TypedHtspRequestCatalogEntry("subscriptionSeek", "SubscriptionSeekRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionSpeed", "SubscriptionSpeedRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionLive", "SubscriptionLiveRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 9),
    TypedHtspRequestCatalogEntry("subscriptionFilterStream", "SubscriptionFilterStreamRequest", "HtspEmptyResponse", HtspAccess.ACCESS_HTSP_STREAMING, 12),
    TypedHtspRequestCatalogEntry("fileOpen", "FileOpenRequest", "FileOpenResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    TypedHtspRequestCatalogEntry("fileRead", "FileReadRequest", "FileReadResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    TypedHtspRequestCatalogEntry("fileClose", "FileCloseRequest", "FileCloseResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    TypedHtspRequestCatalogEntry("fileStat", "FileStatRequest", "FileStatResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
    TypedHtspRequestCatalogEntry("fileSeek", "FileSeekRequest", "FileSeekResponse", HtspAccess.ACCESS_HTSP_RECORDER, 8),
)

public suspend fun HtspConnection.getProfiles(
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetProfilesResponse> =
    call(
        request = GetProfilesRequest(),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getDiskSpace(
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetDiskSpaceResponse> =
    call(
        request = GetDiskSpaceRequest(),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getSysTime(
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetSysTimeResponse> =
    call(
        request = GetSysTimeRequest(),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.enableAsyncMetadata(
    epg: Long? = null,
    lastUpdate: Long? = null,
    epgMaxTime: Long? = null,
    language: String? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    call(
        request = EnableAsyncMetadataRequest(
            epg = epg,
            lastUpdate = lastUpdate,
            epgMaxTime = epgMaxTime,
            language = language,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getChannel(
    channelId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetChannelResponse> =
    call(
        request = GetChannelRequest(
            channelId = channelId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getEvent(
    eventId: Long,
    language: String? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetEventResponse> =
    call(
        request = GetEventRequest(
            eventId = eventId,
            language = language,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getEvents(
    channelId: Long? = null,
    eventId: Long? = null,
    language: String? = null,
    numFollowing: Long? = null,
    maxTime: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetEventsResponse> =
    call(
        request = GetEventsRequest(
            channelId = channelId,
            eventId = eventId,
            language = language,
            numFollowing = numFollowing,
            maxTime = maxTime,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.epgQuery(
    query: String,
    channelId: Long? = null,
    tagId: Long? = null,
    contentType: Long? = null,
    language: String? = null,
    fullText: Boolean? = null,
    mergeText: Boolean? = null,
    full: Long? = null,
    minDurationSeconds: Long? = null,
    maxDurationSeconds: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<EpgQueryResponse> =
    call(
        request = EpgQueryRequest(
            query = query,
            channelId = channelId,
            tagId = tagId,
            contentType = contentType,
            language = language,
            fullText = fullText,
            mergeText = mergeText,
            full = full,
            minDurationSeconds = minDurationSeconds,
            maxDurationSeconds = maxDurationSeconds,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getEpgObject(
    id: Long,
    objectType: HtspEpgObjectType? = HtspEpgObjectType.BROADCAST,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetEpgObjectResponse> =
    call(
        request = GetEpgObjectRequest(
            id = id,
            objectType = objectType,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getDvrConfigs(
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetDvrConfigsResponse> =
    call(
        request = GetDvrConfigsRequest(),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.addDvrEntry(
    selector: AddDvrEntrySelector,
    configName: String? = null,
    language: String? = null,
    title: String? = null,
    subtitle: String? = null,
    summary: String? = null,
    description: String? = null,
    ageRating: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddDvrEntryResponse> =
    call(
        request = AddDvrEntryRequest(
            selector = selector,
            configName = configName,
            language = language,
            title = title,
            subtitle = subtitle,
            summary = summary,
            description = description,
            ageRating = ageRating,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.addDvrEntry(
    eventId: Long,
    configName: String? = null,
    language: String? = null,
    title: String? = null,
    subtitle: String? = null,
    summary: String? = null,
    description: String? = null,
    ageRating: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddDvrEntryResponse> =
    call(
        request = AddDvrEntryRequest(
            selector = AddDvrEntrySelector.Event(eventId),
            configName = configName,
            language = language,
            title = title,
            subtitle = subtitle,
            summary = summary,
            description = description,
            ageRating = ageRating,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.addDvrEntry(
    channelId: Long,
    start: Long,
    stop: Long,
    configName: String? = null,
    language: String? = null,
    title: String? = null,
    subtitle: String? = null,
    summary: String? = null,
    description: String? = null,
    ageRating: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddDvrEntryResponse> =
    call(
        request = AddDvrEntryRequest(
            selector = AddDvrEntrySelector.ExplicitChannelTime(channelId, start, stop),
            configName = configName,
            language = language,
            title = title,
            subtitle = subtitle,
            summary = summary,
            description = description,
            ageRating = ageRating,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.updateDvrEntry(
    entryId: Long,
    channelId: Long? = null,
    configName: String? = null,
    title: String? = null,
    subtitle: String? = null,
    summary: String? = null,
    description: String? = null,
    language: String? = null,
    comment: String? = null,
    playCount: Long? = null,
    playPosition: Long? = null,
    enabled: Long? = null,
    start: Long? = null,
    stop: Long? = null,
    startExtra: Long? = null,
    stopExtra: Long? = null,
    retention: Long? = null,
    removal: Long? = null,
    priority: Long? = null,
    ageRating: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<UpdateDvrEntryResponse> =
    call(
        request = UpdateDvrEntryRequest(
            entryId = entryId,
            channelId = channelId,
            configName = configName,
            title = title,
            subtitle = subtitle,
            summary = summary,
            description = description,
            language = language,
            comment = comment,
            playCount = playCount,
            playPosition = playPosition,
            enabled = enabled,
            start = start,
            stop = stop,
            startExtra = startExtra,
            stopExtra = stopExtra,
            retention = retention,
            removal = removal,
            priority = priority,
            ageRating = ageRating,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.stopDvrEntry(
    entryId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<StopDvrEntryResponse> =
    call(
        request = StopDvrEntryRequest(
            entryId = entryId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.cancelDvrEntry(
    entryId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<CancelDvrEntryResponse> =
    call(
        request = CancelDvrEntryRequest(
            entryId = entryId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.deleteDvrEntry(
    entryId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<DeleteDvrEntryResponse> =
    call(
        request = DeleteDvrEntryRequest(
            entryId = entryId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.addAutorecEntry(
    title: String,
    channel: HtspRecordingRuleChannel? = null,
    minDurationSeconds: Long? = null,
    maxDurationSeconds: Long? = null,
    fullText: Long? = null,
    mergeText: Long? = null,
    duplicateDetection: Long? = null,
    maximumRecordingCount: Long? = null,
    broadcastType: Long? = null,
    startExtraMinutes: Long? = null,
    stopExtraMinutes: Long? = null,
    seriesLinkUri: String? = null,
    approximateStartMinutesSinceMidnight: Int? = null,
    startMinutesSinceMidnight: Int? = null,
    startWindowEndMinutesSinceMidnight: Int? = null,
    enabled: Boolean? = null,
    retentionDays: Long? = null,
    removalDays: Long? = null,
    priority: Long? = null,
    name: String? = null,
    comment: String? = null,
    directory: String? = null,
    configName: String? = null,
    daysOfWeekMask: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddAutorecEntryResponse> =
    call(
        request = AddAutorecEntryRequest(
            title = title,
            channel = channel,
            minDurationSeconds = minDurationSeconds,
            maxDurationSeconds = maxDurationSeconds,
            fullText = fullText,
            mergeText = mergeText,
            duplicateDetection = duplicateDetection,
            maximumRecordingCount = maximumRecordingCount,
            broadcastType = broadcastType,
            startExtraMinutes = startExtraMinutes,
            stopExtraMinutes = stopExtraMinutes,
            seriesLinkUri = seriesLinkUri,
            approximateStartMinutesSinceMidnight = approximateStartMinutesSinceMidnight,
            startMinutesSinceMidnight = startMinutesSinceMidnight,
            startWindowEndMinutesSinceMidnight = startWindowEndMinutesSinceMidnight,
            enabled = enabled,
            retentionDays = retentionDays,
            removalDays = removalDays,
            priority = priority,
            name = name,
            comment = comment,
            directory = directory,
            configName = configName,
            daysOfWeekMask = daysOfWeekMask,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.updateAutorecEntry(
    id: String,
    channel: HtspRecordingRuleChannel? = null,
    minDurationSeconds: Long? = null,
    maxDurationSeconds: Long? = null,
    fullText: Long? = null,
    mergeText: Long? = null,
    duplicateDetection: Long? = null,
    maximumRecordingCount: Long? = null,
    broadcastType: Long? = null,
    startExtraMinutes: Long? = null,
    stopExtraMinutes: Long? = null,
    seriesLinkUri: String? = null,
    startMinutesSinceMidnight: Int? = null,
    startWindowEndMinutesSinceMidnight: Int? = null,
    enabled: Boolean? = null,
    retentionDays: Long? = null,
    removalDays: Long? = null,
    priority: Long? = null,
    name: String? = null,
    comment: String? = null,
    directory: String? = null,
    title: String? = null,
    configName: String? = null,
    daysOfWeekMask: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<UpdateAutorecEntryResponse> =
    call(
        request = UpdateAutorecEntryRequest(
            id = id,
            channel = channel,
            minDurationSeconds = minDurationSeconds,
            maxDurationSeconds = maxDurationSeconds,
            fullText = fullText,
            mergeText = mergeText,
            duplicateDetection = duplicateDetection,
            maximumRecordingCount = maximumRecordingCount,
            broadcastType = broadcastType,
            startExtraMinutes = startExtraMinutes,
            stopExtraMinutes = stopExtraMinutes,
            seriesLinkUri = seriesLinkUri,
            startMinutesSinceMidnight = startMinutesSinceMidnight,
            startWindowEndMinutesSinceMidnight = startWindowEndMinutesSinceMidnight,
            enabled = enabled,
            retentionDays = retentionDays,
            removalDays = removalDays,
            priority = priority,
            name = name,
            comment = comment,
            directory = directory,
            title = title,
            configName = configName,
            daysOfWeekMask = daysOfWeekMask,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.deleteAutorecEntry(
    id: String,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<DeleteAutorecEntryResponse> =
    call(
        request = DeleteAutorecEntryRequest(
            id = id,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.addTimerecEntry(
    title: String,
    channel: HtspRecordingRuleChannel? = null,
    startMinutesSinceMidnight: Long? = null,
    stopMinutesSinceMidnight: Long? = null,
    enabled: Boolean? = null,
    retentionDays: Long? = null,
    removalDays: Long? = null,
    priority: Long? = null,
    name: String? = null,
    comment: String? = null,
    directory: String? = null,
    configName: String? = null,
    daysOfWeekMask: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<AddTimerecEntryResponse> =
    call(
        request = AddTimerecEntryRequest(
            title = title,
            channel = channel,
            startMinutesSinceMidnight = startMinutesSinceMidnight,
            stopMinutesSinceMidnight = stopMinutesSinceMidnight,
            enabled = enabled,
            retentionDays = retentionDays,
            removalDays = removalDays,
            priority = priority,
            name = name,
            comment = comment,
            directory = directory,
            configName = configName,
            daysOfWeekMask = daysOfWeekMask,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.updateTimerecEntry(
    id: String,
    channel: HtspRecordingRuleChannel? = null,
    startMinutesSinceMidnight: Long? = null,
    stopMinutesSinceMidnight: Long? = null,
    enabled: Boolean? = null,
    retentionDays: Long? = null,
    removalDays: Long? = null,
    priority: Long? = null,
    name: String? = null,
    comment: String? = null,
    directory: String? = null,
    title: String? = null,
    configName: String? = null,
    daysOfWeekMask: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<UpdateTimerecEntryResponse> =
    call(
        request = UpdateTimerecEntryRequest(
            id = id,
            channel = channel,
            startMinutesSinceMidnight = startMinutesSinceMidnight,
            stopMinutesSinceMidnight = stopMinutesSinceMidnight,
            enabled = enabled,
            retentionDays = retentionDays,
            removalDays = removalDays,
            priority = priority,
            name = name,
            comment = comment,
            directory = directory,
            title = title,
            configName = configName,
            daysOfWeekMask = daysOfWeekMask,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.deleteTimerecEntry(
    id: String,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<DeleteTimerecEntryResponse> =
    call(
        request = DeleteTimerecEntryRequest(
            id = id,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getDvrCutpoints(
    entryId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetDvrCutpointsResponse> =
    call(
        request = GetDvrCutpointsRequest(
            entryId = entryId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getTicket(
    selector: GetTicketSelector,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetTicketResponse> =
    call(
        request = GetTicketRequest(
            selector = selector,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getTicket(
    selector: GetTicketSelector.Channel,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetTicketResponse> =
    call(
        request = GetTicketRequest(
            selector = selector,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.getTicket(
    selector: GetTicketSelector.Dvr,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<GetTicketResponse> =
    call(
        request = GetTicketRequest(
            selector = selector,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscribe(
    subscriptionId: Long,
    channel: SubscribeChannel,
    profile: String? = null,
    weight: Long? = null,
    ninetyKhz: Long? = null,
    timeshiftPeriodSeconds: Long? = null,
    queueDepth: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<SubscribeResponse> =
    call(
        request = SubscribeRequest(
            subscriptionId = subscriptionId,
            channel = channel,
            profile = profile,
            weight = weight,
            ninetyKhz = ninetyKhz,
            timeshiftPeriodSeconds = timeshiftPeriodSeconds,
            queueDepth = queueDepth,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscribe(
    subscriptionId: Long,
    channelId: Long,
    profile: String? = null,
    weight: Long? = null,
    ninetyKhz: Long? = null,
    timeshiftPeriodSeconds: Long? = null,
    queueDepth: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<SubscribeResponse> =
    call(
        request = SubscribeRequest(
            subscriptionId = subscriptionId,
            channel = SubscribeChannel.Id(channelId),
            profile = profile,
            weight = weight,
            ninetyKhz = ninetyKhz,
            timeshiftPeriodSeconds = timeshiftPeriodSeconds,
            queueDepth = queueDepth,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscribe(
    subscriptionId: Long,
    channelName: String,
    profile: String? = null,
    weight: Long? = null,
    ninetyKhz: Long? = null,
    timeshiftPeriodSeconds: Long? = null,
    queueDepth: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<SubscribeResponse> =
    call(
        request = SubscribeRequest(
            subscriptionId = subscriptionId,
            channel = SubscribeChannel.Name(channelName),
            profile = profile,
            weight = weight,
            ninetyKhz = ninetyKhz,
            timeshiftPeriodSeconds = timeshiftPeriodSeconds,
            queueDepth = queueDepth,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.unsubscribe(
    subscriptionId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    call(
        request = UnsubscribeRequest(
            subscriptionId = subscriptionId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscriptionChangeWeight(
    subscriptionId: Long,
    weight: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    call(
        request = SubscriptionChangeWeightRequest(
            subscriptionId = subscriptionId,
            weight = weight,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscriptionSeek(
    subscriptionId: Long,
    position: SubscriptionSeekPosition,
    absolute: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    call(
        request = SubscriptionSeekRequest(
            subscriptionId = subscriptionId,
            position = position,
            absolute = absolute,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscriptionSeek(
    subscriptionId: Long,
    position: SubscriptionSeekPosition.Time,
    absolute: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    call(
        request = SubscriptionSeekRequest(
            subscriptionId = subscriptionId,
            position = position,
            absolute = absolute,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscriptionSeek(
    subscriptionId: Long,
    position: SubscriptionSeekPosition.Size,
    absolute: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    call(
        request = SubscriptionSeekRequest(
            subscriptionId = subscriptionId,
            position = position,
            absolute = absolute,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscriptionSpeed(
    subscriptionId: Long,
    speed: Int,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    call(
        request = SubscriptionSpeedRequest(
            subscriptionId = subscriptionId,
            speed = speed,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscriptionLive(
    subscriptionId: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    call(
        request = SubscriptionLiveRequest(
            subscriptionId = subscriptionId,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.subscriptionFilterStream(
    subscriptionId: Long,
    enable: List<Long>? = null,
    disable: List<Long>? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<HtspEmptyResponse> =
    call(
        request = SubscriptionFilterStreamRequest(
            subscriptionId = subscriptionId,
            enable = enable,
            disable = disable,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.fileOpen(
    file: String,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileOpenResponse> =
    call(
        request = FileOpenRequest(
            file = file,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.fileRead(
    id: Long,
    size: Long,
    offset: Long? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileReadResponse> =
    call(
        request = FileReadRequest(
            id = id,
            size = size,
            offset = offset,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.fileClose(
    id: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileCloseResponse> =
    call(
        request = FileCloseRequest(
            id = id,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.fileStat(
    id: Long,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileStatResponse> =
    call(
        request = FileStatRequest(
            id = id,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )

public suspend fun HtspConnection.fileSeek(
    id: Long,
    offset: Long,
    whence: FileSeekWhence? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<FileSeekResponse> =
    call(
        request = FileSeekRequest(
            id = id,
            offset = offset,
            whence = whence,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )
