// Generated by docs/htsp-protocol/generate_typed_server_messages.py. DO NOT EDIT.
// The reviewed catalog in that generator is the finite dispatch authority.
package at.bernhardberger.tvheadend.htsp

private data class TypedHtspServerMessageCatalogEntry(
    val method: String,
    val messageType: String,
    val minimumProtocolVersion: Int?,
)

private val typedHtspServerMessageCatalog: List<TypedHtspServerMessageCatalogEntry> = listOf(
    TypedHtspServerMessageCatalogEntry("channelAdd", "HtspChannelAddMessage", null),
    TypedHtspServerMessageCatalogEntry("channelUpdate", "HtspChannelUpdateMessage", null),
    TypedHtspServerMessageCatalogEntry("channelDelete", "HtspChannelDeleteMessage", null),
    TypedHtspServerMessageCatalogEntry("tagAdd", "HtspTagAddMessage", null),
    TypedHtspServerMessageCatalogEntry("tagUpdate", "HtspTagUpdateMessage", null),
    TypedHtspServerMessageCatalogEntry("tagDelete", "HtspTagDeleteMessage", null),
    TypedHtspServerMessageCatalogEntry("dvrEntryAdd", "HtspDvrEntryAddMessage", 4),
    TypedHtspServerMessageCatalogEntry("dvrEntryUpdate", "HtspDvrEntryUpdateMessage", 4),
    TypedHtspServerMessageCatalogEntry("dvrEntryDelete", "HtspDvrEntryDeleteMessage", 4),
    TypedHtspServerMessageCatalogEntry("eventAdd", "HtspEventAddMessage", 6),
    TypedHtspServerMessageCatalogEntry("eventUpdate", "HtspEventUpdateMessage", 6),
    TypedHtspServerMessageCatalogEntry("eventDelete", "HtspEventDeleteMessage", 6),
    TypedHtspServerMessageCatalogEntry("initialSyncCompleted", "HtspInitialSyncCompletedMessage", 2),
    TypedHtspServerMessageCatalogEntry("muxpkt", "HtspMuxPacketMessage", null),
    TypedHtspServerMessageCatalogEntry("queueStatus", "HtspQueueStatusMessage", null),
    TypedHtspServerMessageCatalogEntry("subscriptionStart", "HtspSubscriptionStartMessage", null),
    TypedHtspServerMessageCatalogEntry("subscriptionStop", "HtspSubscriptionStopMessage", null),
    TypedHtspServerMessageCatalogEntry("subscriptionGrace", "HtspSubscriptionGraceMessage", 13),
    TypedHtspServerMessageCatalogEntry("subscriptionStatus", "HtspSubscriptionStatusMessage", null),
    TypedHtspServerMessageCatalogEntry("signalStatus", "HtspSignalStatusMessage", null),
    TypedHtspServerMessageCatalogEntry("subscriptionSpeed", "HtspSubscriptionSpeedMessage", 9),
    TypedHtspServerMessageCatalogEntry("timeshiftStatus", "HtspTimeshiftStatusMessage", 9),
    TypedHtspServerMessageCatalogEntry("subscriptionSkip", "HtspSubscriptionSkipMessage", 9),
)

// Kotlin production names are the internal typealiases below. The backing JVM names are
// deliberately not Java source identifiers; the decoder entry point is also synthetic.
internal sealed interface `HtspServerMessageDecodeResult-internal`
internal data class `HtspServerMessageDecoded-internal`(val message: HtspServerMessage) :
    `HtspServerMessageDecodeResult-internal`
internal data object `HtspServerMessageUnknownMethod-internal` :
    `HtspServerMessageDecodeResult-internal`
internal data object `HtspServerMessageMalformedKnownMessage-internal` :
    `HtspServerMessageDecodeResult-internal`

internal typealias HtspServerMessageDecodeResult = `HtspServerMessageDecodeResult-internal`
internal typealias HtspServerMessageDecoded = `HtspServerMessageDecoded-internal`
internal typealias HtspServerMessageUnknownMethod = `HtspServerMessageUnknownMethod-internal`
internal typealias HtspServerMessageMalformedKnownMessage =
    `HtspServerMessageMalformedKnownMessage-internal`

@JvmSynthetic
internal fun decodeHtspServerMessage(fields: Map<String, Any?>): HtspServerMessageDecodeResult {
    if (fields.containsKey("seq")) return `HtspServerMessageUnknownMethod-internal`
    val method = fields["method"] as? String
        ?: return `HtspServerMessageUnknownMethod-internal`
    return when (method) {
        "channelAdd" -> decodeKnownServerMessage { decodeChannelAdd(fields) }
        "channelUpdate" -> decodeKnownServerMessage { decodeChannelUpdate(fields) }
        "channelDelete" -> decodeKnownServerMessage { decodeChannelDelete(fields) }
        "tagAdd" -> decodeKnownServerMessage { decodeTagAdd(fields) }
        "tagUpdate" -> decodeKnownServerMessage { decodeTagUpdate(fields) }
        "tagDelete" -> decodeKnownServerMessage { decodeTagDelete(fields) }
        "dvrEntryAdd" -> decodeKnownServerMessage { decodeDvrEntryAdd(fields) }
        "dvrEntryUpdate" -> decodeKnownServerMessage { decodeDvrEntryUpdate(fields) }
        "dvrEntryDelete" -> decodeKnownServerMessage { decodeDvrEntryDelete(fields) }
        "eventAdd" -> decodeKnownServerMessage { decodeEventAdd(fields) }
        "eventUpdate" -> decodeKnownServerMessage { decodeEventUpdate(fields) }
        "eventDelete" -> decodeKnownServerMessage { decodeEventDelete(fields) }
        "initialSyncCompleted" -> decodeKnownServerMessage { decodeInitialSyncCompleted(fields) }
        "muxpkt" -> decodeKnownServerMessage { decodeMuxPacket(fields) }
        "queueStatus" -> decodeKnownServerMessage { decodeQueueStatus(fields) }
        "subscriptionStart" -> decodeKnownServerMessage { decodeSubscriptionStart(fields) }
        "subscriptionStop" -> decodeKnownServerMessage { decodeSubscriptionStop(fields) }
        "subscriptionGrace" -> decodeKnownServerMessage { decodeSubscriptionGrace(fields) }
        "subscriptionStatus" -> decodeKnownServerMessage { decodeSubscriptionStatus(fields) }
        "signalStatus" -> decodeKnownServerMessage { decodeSignalStatus(fields) }
        "subscriptionSpeed" -> decodeKnownServerMessage { decodeSubscriptionSpeed(fields) }
        "timeshiftStatus" -> decodeKnownServerMessage { decodeTimeshiftStatus(fields) }
        "subscriptionSkip" -> decodeKnownServerMessage { decodeSubscriptionSkip(fields) }
        else -> `HtspServerMessageUnknownMethod-internal`
    }
}

private fun decodeKnownServerMessage(block: () -> HtspServerMessage): HtspServerMessageDecodeResult =
    try {
        HtspServerMessageDecoded(block())
    } catch (_: IllegalArgumentException) {
        `HtspServerMessageMalformedKnownMessage-internal`
    }

@JvmSynthetic
internal fun typedHtspServerMessageCatalogForTest(): List<Pair<String, String>> =
    typedHtspServerMessageCatalog.map { it.method to it.messageType }
