// Generated by docs/htsp-protocol/generate_typed_request_models.py. DO NOT EDIT.
// The reviewed semantic catalog is docs/htsp-protocol/htsp_surface.py.
package at.bernhardberger.tvheadend.htsp.requests

import at.bernhardberger.tvheadend.htsp.connection.HtspProtocolMappingException
import at.bernhardberger.tvheadend.htsp.jsonapi.*
import at.bernhardberger.tvheadend.htsp.wire.*
import java.util.Collections

/** One stream profile with its stable UUID, display [name], and server [comment]. */
public data class HtspProfile(
    public val profileUuid: String,
    public val name: String,
    public val comment: String,
)

/** One DVR configuration with its stable UUID, display [name], and server [comment]. */
public data class HtspDvrConfig(
    public val dvrConfigUuid: String,
    public val name: String,
    public val comment: String,
)

/** One channel service with name, type, content code, optional conditional-access data, and optional provider name. */
public data class HtspChannelService(
    public val name: String,
    public val type: String,
    public val content: Long,
    public val conditionalAccessId: Long?,
    public val conditionalAccessName: String?,
    public val providerName: String?,
)

/** A complete channel reply with identity, numbering, display data, current and next event IDs, services, and tag IDs. */
public data class HtspChannel(
    public val channelId: Long,
    public val channelUuid: String?,
    public val channelNumber: Long,
    public val channelNumberMinor: Long?,
    public val channelName: String,
    public val channelIcon: String?,
    public val currentEventId: Long,
    public val nextEventId: Long,
    public val services: List<HtspChannelService>,
    public val tagIds: List<Long>,
)

/** A bounded EPG event with channel and time coordinates, localized text, categories, ratings, episode data, imagery, and DVR references. */
public data class HtspEvent(
    public val eventId: Long,
    public val channelId: Long?,
    public val start: Long,
    public val stop: Long,
    public val title: String?,
    public val subtitle: String?,
    public val summary: String?,
    public val description: String?,
    public val categories: List<String>?,
    public val keywords: List<String>?,
    public val seriesLinkUri: String?,
    public val episodeUri: String?,
    public val contentType: Long?,
    public val ageRating: Long?,
    public val ratingLabel: String?,
    public val ratingIcon: String?,
    public val ratingAuthority: String?,
    public val ratingCountry: String?,
    public val starRating: Long?,
    public val copyrightYear: Long?,
    public val firstAired: Long?,
    public val isNew: Long?,
    public val seasonNumber: Long?,
    public val seasonCount: Long?,
    public val episodeNumber: Long?,
    public val episodeCount: Long?,
    public val partNumber: Long?,
    public val partCount: Long?,
    public val episodeOnscreen: String?,
    public val image: String?,
    public val dvrId: Long?,
    public val nextEventId: Long?,
)

/** One DVR cutpoint from [start] through [end] with its unsigned action [type]. */
public data class HtspDvrCutpoint(
    public val start: Long,
    public val end: Long,
    public val type: Long,
)

/** Explicit successful acknowledgement for an RPC with no method-specific reply fields. */
public data object HtspEmptyResponse

/** Handshake observations: negotiated version, optional server labels, copied challenge, web root, language, capabilities, and API version. */
public class HelloResponse(
    public val htspVersion: Long,
    public val serverName: String?,
    public val serverVersion: String?,
    public val challenge: HtspBinary,
    public val webRoot: String?,
    public val language: String?,
    serverCapabilities: List<String>?,
    public val apiVersion: Long?,
) {
    public val serverCapabilities: List<String>? = serverCapabilities?.immutableSnapshot()

    override fun equals(other: Any?): Boolean =
        this === other ||
            other is HelloResponse &&
            htspVersion == other.htspVersion &&
            serverName == other.serverName &&
            serverVersion == other.serverVersion &&
            challenge == other.challenge &&
            webRoot == other.webRoot &&
            language == other.language &&
            serverCapabilities == other.serverCapabilities &&
            apiVersion == other.apiVersion

    override fun hashCode(): Int {
        var result = htspVersion.hashCode()
        result = 31 * result + (serverName?.hashCode() ?: 0)
        result = 31 * result + (serverVersion?.hashCode() ?: 0)
        result = 31 * result + challenge.hashCode()
        result = 31 * result + (webRoot?.hashCode() ?: 0)
        result = 31 * result + (language?.hashCode() ?: 0)
        result = 31 * result + (serverCapabilities?.hashCode() ?: 0)
        result = 31 * result + (apiVersion?.hashCode() ?: 0)
        return result
    }

    override fun toString(): String =
        "HelloResponse(htspVersion=$htspVersion, serverName=$serverName, " +
            "serverVersion=$serverVersion, challenge=$challenge, webRoot=$webRoot, " +
            "language=$language, serverCapabilities=$serverCapabilities, apiVersion=$apiVersion)"
}

/** Authentication access observations and limits; each nullable property was absent or malformed when null. */
public data class AuthenticateResponse(
    public val noAccess: Boolean?,
    public val admin: Boolean?,
    public val streaming: Boolean?,
    public val dvr: Boolean?,
    public val failedDvr: Boolean?,
    public val anonymous: Boolean?,
    public val limitAll: Long?,
    public val limitDvr: Long?,
    public val limitStreaming: Long?,
    public val uiLevel: Long?,
    public val uiLanguage: String?,
)

/** Contains the optional ordered stream-profile list returned by `getProfiles`. */
public data class GetProfilesResponse(public val profiles: List<HtspProfile>?)

/** Contains free and total recording bytes plus the optional used-byte counter. */
public data class GetDiskSpaceResponse(
    public val freeBytes: Long,
    public val usedBytes: Long?,
    public val totalBytes: Long,
)

/** Contains Unix time, the legacy hours-west timezone value, and an optional GMT offset in minutes. */
public data class GetSysTimeResponse(
    public val unixTimeSeconds: Long,
    public val legacyTimezoneHoursWestOfGmt: Int,
    public val gmtOffsetMinutes: Int?,
)

/** Contains the complete channel selected by `getChannel`. */
public data class GetChannelResponse(public val channel: HtspChannel)

/** Contains the complete EPG event selected by `getEvent`. */
public data class GetEventResponse(public val event: HtspEvent)

/** Contains the ordered finite event list selected by `getEvents`. */
public data class GetEventsResponse(public val events: List<HtspEvent>)

/** Closed `epgQuery` reply family containing either event identifiers or complete event values. */
public sealed interface EpgQueryResponse {
    /** Contains only the event identifiers returned by a summary EPG query. */
    public data class EventIds(public val eventIds: List<Long>) : EpgQueryResponse
    /** Contains complete typed events returned by a detailed EPG query. */
    public data class Events(public val events: List<HtspEvent>) : EpgQueryResponse
}

/** Finite object selector encoded by `getEpgObject`; [BROADCAST] selects a broadcast record. */
public enum class HtspEpgObjectType {
    BROADCAST,
}

/** Optional episode numbering with episode, season, and part values, totals, and display text. */
public data class HtspEpgEpisodeNumber(
    public val episodeNumber: Long?,
    public val episodeCount: Long?,
    public val seasonNumber: Long?,
    public val seasonCount: Long?,
    public val partNumber: Long?,
    public val partCount: Long?,
    public val text: String?,
)

/** Bounded detailed broadcast record with timing, channel and event identity, flags, ratings, localized text, numbering, genres, and links; opaque credentials are omitted. */
public data class HtspEpgBroadcastObject(
    public val id: Long,
    public val updatedUnixSeconds: Long,
    public val startUnixSeconds: Long,
    public val stopUnixSeconds: Long,
    public val grabber: String?,
    public val channelUuid: String?,
    public val eventId: Long?,
    public val externalEventId: String?,
    public val widescreen: Boolean,
    public val highDefinition: Boolean,
    public val blackAndWhite: Boolean,
    public val deafSigned: Boolean,
    public val subtitled: Boolean,
    public val audioDescribed: Boolean,
    public val isNew: Boolean,
    public val isRepeat: Boolean,
    public val lines: Long?,
    public val aspectRatio: Long?,
    public val starRating: Long?,
    public val ageRating: Long?,
    public val ratingLabel: String?,
    public val image: String?,
    public val titles: Map<String, String>?,
    public val subtitles: Map<String, String>?,
    public val summaries: Map<String, String>?,
    public val descriptions: Map<String, String>?,
    public val episodeNumber: HtspEpgEpisodeNumber?,
    public val genres: List<Long>?,
    public val copyrightYear: Long?,
    public val firstAiredUnixSeconds: Long?,
    public val categories: List<String>?,
    public val keywords: List<String>?,
    public val seriesLinkUri: String?,
    public val episodeLinkUri: String?,
)

/** Contains the detailed broadcast selected by `getEpgObject`. */
public data class GetEpgObjectResponse(public val broadcast: HtspEpgBroadcastObject)

/** Contains the optional ordered DVR-configuration list visible to the caller. */
public data class GetDvrConfigsResponse(public val configurations: List<HtspDvrConfig>?)

/** Closed request marker implemented by add, update, stop, cancel, and delete DVR entry requests. */
public sealed interface HtspDvrMutationRequest

/** Shared DVR mutation fields: optional success code, untrusted server error text, and an optional entry identifier where applicable. */
public sealed interface HtspDvrMutationResponse {
    public val success: Long?
    public val error: String?
    public val entryId: Long?
        get() = null
}

/** DVR-add reply with optional success code, returned [entryId], and untrusted server [error]. */
public data class AddDvrEntryResponse(
    override public val success: Long?,
    override public val entryId: Long?,
    override public val error: String?,
) : HtspDvrMutationResponse

/** DVR-update result carrying the optional success code and untrusted server error text. */
public data class UpdateDvrEntryResponse(
    override public val success: Long?,
    override public val error: String?,
) : HtspDvrMutationResponse

/** DVR-stop result carrying the optional success code and untrusted server error text. */
public data class StopDvrEntryResponse(
    override public val success: Long?,
    override public val error: String?,
) : HtspDvrMutationResponse

/** DVR-cancel result carrying the optional success code and untrusted server error text. */
public data class CancelDvrEntryResponse(
    override public val success: Long?,
    override public val error: String?,
) : HtspDvrMutationResponse

/** DVR-delete result carrying the optional success code and untrusted server error text. */
public data class DeleteDvrEntryResponse(
    override public val success: Long?,
    override public val error: String?,
) : HtspDvrMutationResponse

/** Closed channel selector for automatic and time-based recording rule requests. */
public sealed interface HtspRecordingRuleChannel {
    /** Selects one recording-rule channel by its complete unsigned [channelId]. */
    @JvmInline
    public value class Id(public val channelId: Long) : HtspRecordingRuleChannel {
        init {
            requireU32("channelId", channelId)
        }
    }

    /** Encodes the signed `-1` any-channel sentinel; update requests may also clear a channel by omitting it. */
    public data object Any : HtspRecordingRuleChannel
}

/** Carries the server identifier returned by an automatic-recording-rule add reply. */
public data class AddAutorecEntryResponse(public val id: String)

/** Carries the strict success discriminator returned for an automatic-recording-rule update request. */
public data object UpdateAutorecEntryResponse

/** Carries the strict success discriminator returned for an automatic-recording-rule delete request. */
public data object DeleteAutorecEntryResponse

/** Carries the server identifier returned by a time-based recording-rule add reply. */
public data class AddTimerecEntryResponse(public val id: String)

/** Carries the strict success discriminator returned for a time-based recording-rule update request. */
public data object UpdateTimerecEntryResponse

/** Carries the strict success discriminator returned for a time-based recording-rule delete request. */
public data object DeleteTimerecEntryResponse

/** Contains the optional ordered cutpoint list for the selected DVR entry. */
public data class GetDvrCutpointsResponse(public val cutpoints: List<HtspDvrCutpoint>?)

/** Closed exactly-one selector for a channel ticket or a DVR ticket. */
public sealed interface GetTicketSelector {
    /** Selects a ticket source by complete unsigned channel identifier. */
    @JvmInline
    public value class Channel(public val channelId: Long) : GetTicketSelector {
        init {
            requireU32("channelId", channelId)
        }
    }

    /** Selects a ticket source by complete unsigned DVR identifier. */
    @JvmInline
    public value class Dvr(public val dvrId: Long) : GetTicketSelector {
        init {
            requireU32("dvrId", dvrId)
        }
    }
}

/** Credential-bearing ticket reply containing the access [path] and [ticket]; string rendering redacts both. */
public class GetTicketResponse(
    public val path: String,
    public val ticket: String,
) {
    override fun toString(): String =
        "GetTicketResponse(path=<redacted>, ticket=<redacted>)"
}

/** Opened file handle [id] with source-coupled optional size and modification-time metadata. */
public data class FileOpenResponse(
    public val id: Long,
    public val sizeBytes: Long?,
    public val modifiedAtUnixSeconds: Long?,
)

/** Contains one defensively copied bounded payload; an empty payload is a valid successful read. */
public data class FileReadResponse(public val data: HtspBinary)

/** Explicit successful empty acknowledgement returned for a protocol file-close request. */
public data object FileCloseResponse

/** Optional size and modification time for an open file handle; the pair is absent together when unavailable. */
public data class FileStatResponse(
    public val sizeBytes: Long?,
    public val modifiedAtUnixSeconds: Long?,
)

/** Contains the successful absolute non-negative file offset after a seek. */
public data class FileSeekResponse(public val offset: Long)

/** Finite file-seek origin vocabulary: start, current position, or end; a null request value omits the field. */
public enum class FileSeekWhence {
    SET,
    CURRENT,
    END,
}

/** Negotiated subscription values: optional 90 kHz mode, normalized-timestamp flag, scheduling weight, and timeshift period in seconds. */
public data class SubscribeResponse(
    public val ninetyKhz: Long?,
    public val normalizedTimestamps: Long?,
    public val weight: Long?,
    public val timeshiftPeriodSeconds: Long?,
)

/** Carries the requested unsigned HTSP version and exact client name for the `hello` exchange. */
public data class HelloRequest(
    public val htspVersion: Long,
    public val clientName: String,
) : HtspRequest<HelloResponse>(
    method = "hello",
    access = HtspAccess.ACCESS_ANONYMOUS,
    minimumProtocolVersion = null,
) {
    init {
        requireU32("htspVersion", htspVersion)
    }
}

/** Bare authentication request; credentials belong to the connection envelope rather than constructor properties. */
public class AuthenticateRequest : HtspRequest<AuthenticateResponse>(
    method = "authenticate",
    access = HtspAccess.ACCESS_ANONYMOUS,
    minimumProtocolVersion = null,
)

/** Requests the stream-profile list and carries no method-specific parameters. */
public class GetProfilesRequest : HtspRequest<GetProfilesResponse>(
    method = "getProfiles",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 16,
)

/** Requests recording-storage counters and carries no method-specific parameters. */
public class GetDiskSpaceRequest : HtspRequest<GetDiskSpaceResponse>(
    method = "getDiskSpace",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 3,
)

/** Requests the server clock and timezone observations without method-specific parameters. */
public class GetSysTimeRequest : HtspRequest<GetSysTimeResponse>(
    method = "getSysTime",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 3,
)

/** Selects asynchronous metadata options: EPG inclusion, update frontier, EPG maximum time, and language; null omits each field. */
public data class EnableAsyncMetadataRequest(
    public val epg: Long? = null,
    public val lastUpdate: Long? = null,
    public val epgMaxTime: Long? = null,
    public val language: String? = null,
) : HtspRequest<HtspEmptyResponse>(
    method = "enableAsyncMetadata",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 6.takeIf {
            epg != null || lastUpdate != null || epgMaxTime != null || language != null
        },
) {
    init {
        epg?.let { requireU32("epg", it) }
    }
}

/** Selects one channel by complete unsigned [channelId]. */
public data class GetChannelRequest(public val channelId: Long) : HtspRequest<GetChannelResponse>(
    method = "getChannel",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 14,
) {
    init {
        requireU32("channelId", channelId)
    }
}

/** Selects one event by complete unsigned [eventId] and optional response [language]. */
public data class GetEventRequest(
    public val eventId: Long,
    public val language: String? = null,
) : HtspRequest<GetEventResponse>(
    method = "getEvent",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 6.takeIf { language != null },
) {
    init {
        requireU32("eventId", eventId)
    }
}

/** Selects an event set by optional channel or event ID, language, following count, and maximum Unix time. */
public data class GetEventsRequest(
    public val channelId: Long? = null,
    public val eventId: Long? = null,
    public val language: String? = null,
    public val numFollowing: Long? = null,
    public val maxTime: Long? = null,
) : HtspRequest<GetEventsResponse>(
    method = "getEvents",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = if (
            channelId != null || eventId != null || language != null || numFollowing != null || maxTime != null
        ) 6 else 4,
) {
    init {
        channelId?.let { requireU32("channelId", it) }
        eventId?.let { requireU32("eventId", it) }
        numFollowing?.let { requireU32("numFollowing", it) }
    }
}

/** Carries required search [query] plus optional channel, tag, content, language, text-mode, detail, and duration filters. */
public data class EpgQueryRequest(
    public val query: String,
    public val channelId: Long? = null,
    public val tagId: Long? = null,
    public val contentType: Long? = null,
    public val language: String? = null,
    public val fullText: Boolean? = null,
    public val mergeText: Boolean? = null,
    public val full: Long? = null,
    public val minDurationSeconds: Long? = null,
    public val maxDurationSeconds: Long? = null,
) : HtspRequest<EpgQueryResponse>(
    method = "epgQuery",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = maxVersion(
            4,
            6.takeIf { language != null },
            13.takeIf { minDurationSeconds != null || maxDurationSeconds != null },
        ),
) {
    init {
        channelId?.let { requireU32("channelId", it) }
        tagId?.let { requireU32("tagId", it) }
        contentType?.let { requireU32("contentType", it) }
        full?.let { requireU32("full", it) }
        minDurationSeconds?.let { requireU32("minduration", it) }
        maxDurationSeconds?.let { requireU32("maxduration", it) }
    }
}

/** Selects a detailed EPG object by unsigned [id] and optional finite [objectType]. */
public data class GetEpgObjectRequest(
    public val id: Long,
    public val objectType: HtspEpgObjectType? = HtspEpgObjectType.BROADCAST,
) : HtspRequest<GetEpgObjectResponse>(
    method = "getEpgObject",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = null,
) {
    init {
        requireU32("id", id)
    }
}

/** Requests visible DVR configurations and carries no method-specific parameters. */
public class GetDvrConfigsRequest : HtspRequest<GetDvrConfigsResponse>(
    method = "getDvrConfigs",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 16,
)

/** Closed DVR scheduling selector: an existing event or an explicit channel and time range. */
public sealed interface AddDvrEntrySelector {
    /** Selects an existing event by complete unsigned [eventId] for DVR scheduling. */
    public data class Event(public val eventId: Long) : AddDvrEntrySelector {
        init {
            requireU32("eventId", eventId)
        }
    }

    /** Selects a complete unsigned [channelId] and signed [start] and [stop] coordinates for DVR scheduling. */
    public data class ExplicitChannelTime(
        public val channelId: Long,
        public val start: Long,
        public val stop: Long,
    ) : AddDvrEntrySelector {
        init {
            requireU32("channelId", channelId)
        }
    }
}

/** Requests DVR scheduling from exactly one [selector] with optional configuration, language, programme text, and age rating. */
public data class AddDvrEntryRequest(
    public val selector: AddDvrEntrySelector,
    public val configName: String? = null,
    public val language: String? = null,
    public val title: String? = null,
    public val subtitle: String? = null,
    public val summary: String? = null,
    public val description: String? = null,
    public val ageRating: Long? = null,
) : HtspRequest<AddDvrEntryResponse>(
    method = "addDvrEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = maxVersion(
            4,
            5.takeIf { selector is AddDvrEntrySelector.ExplicitChannelTime },
            6.takeIf { title != null },
            20.takeIf { subtitle != null },
            5.takeIf { description != null },
            36.takeIf { ageRating != null },
        ),
), HtspDvrMutationRequest {
    init {
        ageRating?.let { requireU32("ageRating", it) }
    }
}

/** Identifies one DVR entry and carries optional channel, configuration, programme text, progress, enablement, timing, retention, priority, and age rating changes. */
public data class UpdateDvrEntryRequest(
    public val entryId: Long,
    public val channelId: Long? = null,
    public val configName: String? = null,
    public val title: String? = null,
    public val subtitle: String? = null,
    public val summary: String? = null,
    public val description: String? = null,
    public val language: String? = null,
    public val comment: String? = null,
    public val playCount: Long? = null,
    public val playPosition: Long? = null,
    public val enabled: Long? = null,
    public val start: Long? = null,
    public val stop: Long? = null,
    public val startExtra: Long? = null,
    public val stopExtra: Long? = null,
    public val retention: Long? = null,
    public val removal: Long? = null,
    public val priority: Long? = null,
    public val ageRating: Long? = null,
) : HtspRequest<UpdateDvrEntryResponse>(
    method = "updateDvrEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = maxVersion(
            5,
            22.takeIf { channelId != null },
            21.takeIf { subtitle != null },
            6.takeIf { description != null },
            42.takeIf { comment != null },
            27.takeIf { playCount != null || playPosition != null },
            23.takeIf { enabled != null },
            6.takeIf { startExtra != null || stopExtra != null },
            13.takeIf { retention != null || priority != null },
            36.takeIf { ageRating != null },
        ),
), HtspDvrMutationRequest {
    init {
        requireU32("id", entryId)
        channelId?.let { requireU32("channelId", it) }
        playCount?.let { requireU32("playCount", it) }
        playPosition?.let { requireU32("playPosition", it) }
        retention?.let { requireU32("retention", it) }
        removal?.let { requireU32("removal", it) }
        priority?.let { requireU32("priority", it) }
        ageRating?.let { requireU32("ageRating", it) }
    }
}

/** Selects one DVR entry by complete unsigned [entryId] for stopping. */
public data class StopDvrEntryRequest(public val entryId: Long) : HtspRequest<StopDvrEntryResponse>(
    method = "stopDvrEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = null,
), HtspDvrMutationRequest {
    init {
        requireU32("id", entryId)
    }
}

/** Selects one DVR entry by complete unsigned [entryId] for cancellation. */
public data class CancelDvrEntryRequest(public val entryId: Long) : HtspRequest<CancelDvrEntryResponse>(
    method = "cancelDvrEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 5,
), HtspDvrMutationRequest {
    init {
        requireU32("id", entryId)
    }
}

/** Selects one DVR entry by complete unsigned [entryId] for deletion. */
public data class DeleteDvrEntryRequest(public val entryId: Long) : HtspRequest<DeleteDvrEntryResponse>(
    method = "deleteDvrEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 4,
), HtspDvrMutationRequest {
    init {
        requireU32("id", entryId)
    }
}

/** Defines an automatic recording rule with required title and optional channel, text, duration, time-window, count, schedule, retention, ownership, and configuration fields. */
public data class AddAutorecEntryRequest(
    public val title: String,
    public val channel: HtspRecordingRuleChannel? = null,
    public val minDurationSeconds: Long? = null,
    public val maxDurationSeconds: Long? = null,
    public val fullText: Long? = null,
    public val mergeText: Long? = null,
    public val duplicateDetection: Long? = null,
    public val maximumRecordingCount: Long? = null,
    public val broadcastType: Long? = null,
    public val startExtraMinutes: Long? = null,
    public val stopExtraMinutes: Long? = null,
    public val seriesLinkUri: String? = null,
    public val approximateStartMinutesSinceMidnight: Int? = null,
    public val startMinutesSinceMidnight: Int? = null,
    public val startWindowEndMinutesSinceMidnight: Int? = null,
    public val enabled: Boolean? = null,
    public val retentionDays: Long? = null,
    public val removalDays: Long? = null,
    public val priority: Long? = null,
    public val name: String? = null,
    public val comment: String? = null,
    public val directory: String? = null,
    public val configName: String? = null,
    public val daysOfWeekMask: Long? = null,
) : HtspRequest<AddAutorecEntryResponse>(
    method = "addAutorecEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = maxVersion(
            13,
            25.takeIf { channel is HtspRecordingRuleChannel.Any },
            18.takeIf {
                name != null || startMinutesSinceMidnight != null || startWindowEndMinutesSinceMidnight != null
            },
            19.takeIf { enabled != null || directory != null },
            20.takeIf { fullText != null || duplicateDetection != null },
            39.takeIf { broadcastType != null },
            42.takeIf { comment != null },
        ),
) {
    init {
        validateAutorecU32Fields()
    }
}

/** Identifies an automatic recording rule and carries optional channel, matching, duration, schedule, count, retention, ownership, title, and configuration changes. */
public data class UpdateAutorecEntryRequest(
    public val id: String,
    public val channel: HtspRecordingRuleChannel? = null,
    public val minDurationSeconds: Long? = null,
    public val maxDurationSeconds: Long? = null,
    public val fullText: Long? = null,
    public val mergeText: Long? = null,
    public val duplicateDetection: Long? = null,
    public val maximumRecordingCount: Long? = null,
    public val broadcastType: Long? = null,
    public val startExtraMinutes: Long? = null,
    public val stopExtraMinutes: Long? = null,
    public val seriesLinkUri: String? = null,
    public val startMinutesSinceMidnight: Int? = null,
    public val startWindowEndMinutesSinceMidnight: Int? = null,
    public val enabled: Boolean? = null,
    public val retentionDays: Long? = null,
    public val removalDays: Long? = null,
    public val priority: Long? = null,
    public val name: String? = null,
    public val comment: String? = null,
    public val directory: String? = null,
    public val title: String? = null,
    public val configName: String? = null,
    public val daysOfWeekMask: Long? = null,
) : HtspRequest<UpdateAutorecEntryResponse>(
    method = "updateAutorecEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = maxVersion(
            25,
            39.takeIf { broadcastType != null },
            42.takeIf { comment != null },
        ),
) {
    init {
        validateAutorecU32Fields()
    }
}

/** Selects one automatic recording rule by string [id] for deletion. */
public data class DeleteAutorecEntryRequest(public val id: String) : HtspRequest<DeleteAutorecEntryResponse>(
    method = "deleteAutorecEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 13,
)

/** Defines a time-based recording rule with title and optional channel, daily interval, enablement, days, priority, retention, ownership, and configuration fields. */
public data class AddTimerecEntryRequest(
    public val title: String,
    public val channel: HtspRecordingRuleChannel? = null,
    public val startMinutesSinceMidnight: Long? = null,
    public val stopMinutesSinceMidnight: Long? = null,
    public val enabled: Boolean? = null,
    public val retentionDays: Long? = null,
    public val removalDays: Long? = null,
    public val priority: Long? = null,
    public val name: String? = null,
    public val comment: String? = null,
    public val directory: String? = null,
    public val configName: String? = null,
    public val daysOfWeekMask: Long? = null,
) : HtspRequest<AddTimerecEntryResponse>(
    method = "addTimerecEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = maxVersion(
            18,
            25.takeIf { channel is HtspRecordingRuleChannel.Any },
            19.takeIf { enabled != null || directory != null },
            42.takeIf { comment != null },
        ),
) {
    init {
        validateTimerecU32Fields()
    }
}

/** Identifies a time-based recording rule and carries optional channel, daily interval, enablement, days, policy, ownership, title, and configuration changes. */
public data class UpdateTimerecEntryRequest(
    public val id: String,
    public val channel: HtspRecordingRuleChannel? = null,
    public val startMinutesSinceMidnight: Long? = null,
    public val stopMinutesSinceMidnight: Long? = null,
    public val enabled: Boolean? = null,
    public val retentionDays: Long? = null,
    public val removalDays: Long? = null,
    public val priority: Long? = null,
    public val name: String? = null,
    public val comment: String? = null,
    public val directory: String? = null,
    public val title: String? = null,
    public val configName: String? = null,
    public val daysOfWeekMask: Long? = null,
) : HtspRequest<UpdateTimerecEntryResponse>(
    method = "updateTimerecEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = maxVersion(25, 42.takeIf { comment != null }),
) {
    init {
        validateTimerecU32Fields()
    }
}

/** Selects one time-based recording rule by string [id] for deletion. */
public data class DeleteTimerecEntryRequest(public val id: String) : HtspRequest<DeleteTimerecEntryResponse>(
    method = "deleteTimerecEntry",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 18,
)

/** Selects one DVR entry by complete unsigned [entryId] for cutpoint retrieval. */
public data class GetDvrCutpointsRequest(public val entryId: Long) : HtspRequest<GetDvrCutpointsResponse>(
    method = "getDvrCutpoints",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 12,
) {
    init {
        requireU32("id", entryId)
    }
}

/** Carries exactly one channel-or-DVR [selector] for temporary ticket retrieval. */
public data class GetTicketRequest(
    public val selector: GetTicketSelector,
) : HtspRequest<GetTicketResponse>(
    method = "getTicket",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 5,
)

/** Closed exactly-one subscription channel selector by unsigned ID or exact name. */
public sealed interface SubscribeChannel {
    /** Selects a subscription channel by complete unsigned [channelId]. */
    public data class Id(public val channelId: Long) : SubscribeChannel {
        init {
            requireU32("channelId", channelId)
        }
    }

    /** Selects a subscription channel by exact [channelName]. */
    public data class Name(public val channelName: String) : SubscribeChannel
}

/** Requests [subscriptionId] for exactly one [channel] with optional profile, weight, 90 kHz timestamps, timeshift period, and queue depth. */
public data class SubscribeRequest(
    public val subscriptionId: Long,
    public val channel: SubscribeChannel,
    public val profile: String? = null,
    public val weight: Long? = null,
    public val ninetyKhz: Long? = null,
    public val timeshiftPeriodSeconds: Long? = null,
    public val queueDepth: Long? = null,
) : HtspRequest<SubscribeResponse>(
    method = "subscribe",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = maxVersion(
            null,
            16.takeIf { profile != null },
            7.takeIf { ninetyKhz != null || queueDepth != null },
            9.takeIf { timeshiftPeriodSeconds != null },
        ),
) {
    init {
        requireU32("subscriptionId", subscriptionId)
        weight?.let { requireU32("weight", it) }
        ninetyKhz?.let { requireU32("90khz", it) }
        timeshiftPeriodSeconds?.let { requireU32("timeshiftPeriod", it) }
        queueDepth?.let { requireU32("queueDepth", it) }
    }
}

/** Selects one subscription by complete unsigned [subscriptionId] for termination. */
public data class UnsubscribeRequest(
    public val subscriptionId: Long,
) : HtspRequest<HtspEmptyResponse>(
    method = "unsubscribe",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = null,
) {
    init {
        requireU32("subscriptionId", subscriptionId)
    }
}

/** Selects one subscription and optionally supplies its new unsigned scheduling [weight]. */
public data class SubscriptionChangeWeightRequest(
    public val subscriptionId: Long,
    public val weight: Long? = null,
) : HtspRequest<HtspEmptyResponse>(
    method = "subscriptionChangeWeight",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 5,
) {
    init {
        requireU32("subscriptionId", subscriptionId)
        weight?.let { requireU32("weight", it) }
    }
}

/** Closed signed subscription coordinate: media time or byte size. */
public sealed interface SubscriptionSeekPosition {
    /** Carries a signed media [time] coordinate for seek or skip. */
    public data class Time(public val time: Long) : SubscriptionSeekPosition
    /** Carries a signed byte [size] coordinate for seek or skip. */
    public data class Size(public val size: Long) : SubscriptionSeekPosition
}

/** Selects a subscription, one signed [position], and an optional unsigned [absolute] flag for seeking. */
public data class SubscriptionSeekRequest(
    public val subscriptionId: Long,
    public val position: SubscriptionSeekPosition,
    public val absolute: Long? = null,
) : HtspRequest<HtspEmptyResponse>(
    method = "subscriptionSeek",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 9,
) {
    init {
        requireU32("subscriptionId", subscriptionId)
        absolute?.let { requireU32("absolute", it) }
    }
}

/** Selects a subscription, one signed [position], and an optional unsigned [absolute] flag for skipping. */
public data class SubscriptionSkipRequest(
    public val subscriptionId: Long,
    public val position: SubscriptionSeekPosition,
    public val absolute: Long? = null,
) : HtspRequest<HtspEmptyResponse>(
    method = "subscriptionSkip",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 9,
) {
    init {
        requireU32("subscriptionId", subscriptionId)
        absolute?.let { requireU32("absolute", it) }
    }
}

/** Selects a subscription and carries the requested signed playback [speed]. */
public data class SubscriptionSpeedRequest(
    public val subscriptionId: Long,
    public val speed: Int,
) : HtspRequest<HtspEmptyResponse>(
    method = "subscriptionSpeed",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 9,
) {
    init {
        requireU32("subscriptionId", subscriptionId)
    }
}

/** Selects one subscription by complete unsigned [subscriptionId] and requests live mode. */
public data class SubscriptionLiveRequest(
    public val subscriptionId: Long,
) : HtspRequest<HtspEmptyResponse>(
    method = "subscriptionLive",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 9,
) {
    init {
        requireU32("subscriptionId", subscriptionId)
    }
}

/** Selects one subscription and immutable optional stream-index lists to enable and disable. */
public class SubscriptionFilterStreamRequest(
    public val subscriptionId: Long,
    enable: List<Long>? = null,
    disable: List<Long>? = null,
) : HtspRequest<HtspEmptyResponse>(
    method = "subscriptionFilterStream",
    access = HtspAccess.ACCESS_HTSP_STREAMING,
    minimumProtocolVersion = 12,
) {
    public val enable: List<Long>? = enable?.immutableSnapshot()
    public val disable: List<Long>? = disable?.immutableSnapshot()

    init {
        requireU32("subscriptionId", subscriptionId)
        this.enable?.forEach { requireU32("enable", it) }
        this.disable?.forEach { requireU32("disable", it) }
    }
}

/** Carries the exact protocol [file] selector without path normalization; diagnostics redact it. */
public data class FileOpenRequest(public val file: String) : HtspRequest<FileOpenResponse>(
    method = "fileOpen",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 8,
) {
    override fun toString(): String = "FileOpenRequest(file=<redacted>)"
}

/** Selects an open file [id], bounded byte [size], and optional signed [offset] for one read. */
public data class FileReadRequest(
    public val id: Long,
    public val size: Long,
    public val offset: Long? = null,
) : HtspRequest<FileReadResponse>(
    method = "fileRead",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 8,
) {
    init {
        requireU32("id", id)
        require(size in 0L..MAX_FILE_READ_SIZE_BYTES) {
                    "size must be between zero and 16 MiB"
                }
    }
}

/** Selects an open file [id] and optional recording position and play-count values; null omits each progress field. */
public data class FileCloseRequest(
    public val id: Long,
    public val playPositionSeconds: Long? = null,
    public val playCount: Long? = null,
) : HtspRequest<FileCloseResponse>(
    method = "fileClose",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = if (playPositionSeconds != null || playCount != null) 27 else 8,
) {
    init {
        requireU32("id", id)
        playPositionSeconds?.let { requireU32("playPositionSeconds", it) }
        playCount?.let { requireU32("playCount", it) }
    }
}

/** Selects an open protocol file handle by complete unsigned [id] for metadata retrieval. */
public data class FileStatRequest(public val id: Long) : HtspRequest<FileStatResponse>(
    method = "fileStat",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 8,
) {
    init {
        requireU32("id", id)
    }
}

/** Selects an open file [id], signed [offset], and optional finite [whence] origin. */
public data class FileSeekRequest(
    public val id: Long,
    public val offset: Long,
    public val whence: FileSeekWhence? = null,
) : HtspRequest<FileSeekResponse>(
    method = "fileSeek",
    access = HtspAccess.ACCESS_HTSP_RECORDER,
    minimumProtocolVersion = 8,
) {
    init {
        requireU32("id", id)
    }
}

@OptIn(HtspJsonApi::class)
internal object `HtspRequestCodecs-internal` {
    @JvmSynthetic
    internal fun encode(request: HtspRequest<*>): LinkedHashMap<String, Any?> = when (request) {
        is ApiRequest -> linkedMapOf<String, Any?>("path" to request.path)
            .putIfNotNull("args", request.args?.toWireValue())

        is HelloRequest -> linkedMapOf(
            "htspversion" to request.htspVersion,
            "clientname" to request.clientName,
        )

        is AuthenticateRequest -> linkedMapOf()

        is GetProfilesRequest -> linkedMapOf()

        is GetDiskSpaceRequest -> linkedMapOf()

        is GetSysTimeRequest -> linkedMapOf()

        is EnableAsyncMetadataRequest -> linkedMapOf<String, Any?>()
            .putIfNotNull("epg", request.epg)
            .putIfNotNull("lastUpdate", request.lastUpdate)
            .putIfNotNull("epgMaxTime", request.epgMaxTime)
            .putIfNotNull("language", request.language)

        is GetChannelRequest -> linkedMapOf("channelId" to request.channelId)

        is GetEventRequest -> linkedMapOf<String, Any?>("eventId" to request.eventId)
            .putIfNotNull("language", request.language)

        is GetEventsRequest -> linkedMapOf<String, Any?>()
            .putIfNotNull("channelId", request.channelId)
            .putIfNotNull("eventId", request.eventId)
            .putIfNotNull("language", request.language)
            .putIfNotNull("numFollowing", request.numFollowing)
            .putIfNotNull("maxTime", request.maxTime)

        is EpgQueryRequest -> linkedMapOf<String, Any?>("query" to request.query)
            .putIfNotNull("channelId", request.channelId)
            .putIfNotNull("tagId", request.tagId)
            .putIfNotNull("contentType", request.contentType)
            .putIfNotNull("language", request.language)
            .putIfNotNull("fulltext", request.fullText)
            .putIfNotNull("mergetext", request.mergeText)
            .putIfNotNull("full", request.full)
            .putIfNotNull("minduration", request.minDurationSeconds)
            .putIfNotNull("maxduration", request.maxDurationSeconds)

        is GetEpgObjectRequest -> linkedMapOf<String, Any?>("id" to request.id)
            .putIfNotNull(
                "type",
                request.objectType?.let { objectType ->
                    when (objectType) {
                        HtspEpgObjectType.BROADCAST -> 1L
                    }
                },
            )

        is GetDvrConfigsRequest -> linkedMapOf()

        is AddDvrEntryRequest -> linkedMapOf<String, Any?>().apply {
            if (request.selector is AddDvrEntrySelector.ExplicitChannelTime) {
                put("channelId", request.selector.channelId)
            }
            if (request.selector is AddDvrEntrySelector.Event) {
                put("eventId", request.selector.eventId)
            }
            putIfNotNull("configName", request.configName)
            putIfNotNull("language", request.language)
            if (request.selector is AddDvrEntrySelector.ExplicitChannelTime) {
                put("start", request.selector.start)
                put("stop", request.selector.stop)
            }
            putIfNotNull("title", request.title)
            putIfNotNull("subtitle", request.subtitle)
            putIfNotNull("summary", request.summary)
            putIfNotNull("description", request.description)
            putIfNotNull("ageRating", request.ageRating)
        }

        is UpdateDvrEntryRequest -> linkedMapOf<String, Any?>()
            .putIfNotNull("channelId", request.channelId)
            .putIfNotNull("configName", request.configName)
            .putIfNotNull("title", request.title)
            .putIfNotNull("subtitle", request.subtitle)
            .putIfNotNull("summary", request.summary)
            .putIfNotNull("description", request.description)
            .putIfNotNull("language", request.language)
            .putIfNotNull("comment", request.comment)
            .putIfNotNull("playcount", request.playCount)
            .putIfNotNull("playposition", request.playPosition)
            .putIfNotNull("enabled", request.enabled)
            .putIfNotNull("start", request.start)
            .putIfNotNull("stop", request.stop)
            .putIfNotNull("startExtra", request.startExtra)
            .putIfNotNull("stopExtra", request.stopExtra)
            .putIfNotNull("retention", request.retention)
            .putIfNotNull("removal", request.removal)
            .putIfNotNull("priority", request.priority)
            .putIfNotNull("ageRating", request.ageRating)
            .apply { put("id", request.entryId) }

        is StopDvrEntryRequest -> linkedMapOf("id" to request.entryId)

        is CancelDvrEntryRequest -> linkedMapOf("id" to request.entryId)

        is DeleteDvrEntryRequest -> linkedMapOf("id" to request.entryId)

        is AddAutorecEntryRequest -> linkedMapOf<String, Any?>("title" to request.title)
            .putRecordingRuleChannel(request.channel)
            .putIfNotNull("minduration", request.minDurationSeconds)
            .putIfNotNull("maxduration", request.maxDurationSeconds)
            .putIfNotNull("fulltext", request.fullText)
            .putIfNotNull("mergetext", request.mergeText)
            .putIfNotNull("dupDetect", request.duplicateDetection)
            .putIfNotNull("maxCount", request.maximumRecordingCount)
            .putIfNotNull("broadcastType", request.broadcastType)
            .putIfNotNull("startExtra", request.startExtraMinutes)
            .putIfNotNull("stopExtra", request.stopExtraMinutes)
            .putIfNotNull("serieslinkUri", request.seriesLinkUri)
            .putIfNotNull("approxTime", request.approximateStartMinutesSinceMidnight)
            .putIfNotNull("start", request.startMinutesSinceMidnight)
            .putIfNotNull("startWindow", request.startWindowEndMinutesSinceMidnight)
            .putIfNotNull("enabled", request.enabled?.toWireFlag())
            .putIfNotNull("retention", request.retentionDays)
            .putIfNotNull("removal", request.removalDays)
            .putIfNotNull("priority", request.priority)
            .putIfNotNull("name", request.name)
            .putIfNotNull("comment", request.comment)
            .putIfNotNull("directory", request.directory)
            .putIfNotNull("configName", request.configName)
            .putIfNotNull("daysOfWeek", request.daysOfWeekMask)

        is UpdateAutorecEntryRequest -> linkedMapOf<String, Any?>("id" to request.id)
            .putRecordingRuleChannel(request.channel)
            .putIfNotNull("minduration", request.minDurationSeconds)
            .putIfNotNull("maxduration", request.maxDurationSeconds)
            .putIfNotNull("fulltext", request.fullText)
            .putIfNotNull("mergetext", request.mergeText)
            .putIfNotNull("dupDetect", request.duplicateDetection)
            .putIfNotNull("maxCount", request.maximumRecordingCount)
            .putIfNotNull("broadcastType", request.broadcastType)
            .putIfNotNull("startExtra", request.startExtraMinutes)
            .putIfNotNull("stopExtra", request.stopExtraMinutes)
            .putIfNotNull("serieslinkUri", request.seriesLinkUri)
            .putIfNotNull("start", request.startMinutesSinceMidnight)
            .putIfNotNull("startWindow", request.startWindowEndMinutesSinceMidnight)
            .putIfNotNull("enabled", request.enabled?.toWireFlag())
            .putIfNotNull("retention", request.retentionDays)
            .putIfNotNull("removal", request.removalDays)
            .putIfNotNull("priority", request.priority)
            .putIfNotNull("name", request.name)
            .putIfNotNull("comment", request.comment)
            .putIfNotNull("directory", request.directory)
            .putIfNotNull("title", request.title)
            .putIfNotNull("configName", request.configName)
            .putIfNotNull("daysOfWeek", request.daysOfWeekMask)

        is DeleteAutorecEntryRequest -> linkedMapOf("id" to request.id)

        is AddTimerecEntryRequest -> linkedMapOf<String, Any?>("title" to request.title)
            .putRecordingRuleChannel(request.channel)
            .putIfNotNull("start", request.startMinutesSinceMidnight)
            .putIfNotNull("stop", request.stopMinutesSinceMidnight)
            .putIfNotNull("enabled", request.enabled?.toWireFlag())
            .putIfNotNull("retention", request.retentionDays)
            .putIfNotNull("removal", request.removalDays)
            .putIfNotNull("priority", request.priority)
            .putIfNotNull("name", request.name)
            .putIfNotNull("comment", request.comment)
            .putIfNotNull("directory", request.directory)
            .putIfNotNull("configName", request.configName)
            .putIfNotNull("daysOfWeek", request.daysOfWeekMask)

        is UpdateTimerecEntryRequest -> linkedMapOf<String, Any?>("id" to request.id)
            .putRecordingRuleChannel(request.channel)
            .putIfNotNull("start", request.startMinutesSinceMidnight)
            .putIfNotNull("stop", request.stopMinutesSinceMidnight)
            .putIfNotNull("enabled", request.enabled?.toWireFlag())
            .putIfNotNull("retention", request.retentionDays)
            .putIfNotNull("removal", request.removalDays)
            .putIfNotNull("priority", request.priority)
            .putIfNotNull("name", request.name)
            .putIfNotNull("comment", request.comment)
            .putIfNotNull("directory", request.directory)
            .putIfNotNull("title", request.title)
            .putIfNotNull("configName", request.configName)
            .putIfNotNull("daysOfWeek", request.daysOfWeekMask)

        is DeleteTimerecEntryRequest -> linkedMapOf("id" to request.id)

        is GetDvrCutpointsRequest -> linkedMapOf("id" to request.entryId)

        is GetTicketRequest -> when (val selector = request.selector) {
            is GetTicketSelector.Channel -> linkedMapOf("channelId" to selector.channelId)
            is GetTicketSelector.Dvr -> linkedMapOf("dvrId" to selector.dvrId)
        }

        is SubscribeRequest -> linkedMapOf<String, Any?>(
            "subscriptionId" to request.subscriptionId,
        ).apply {
            when (val channel = request.channel) {
                is SubscribeChannel.Id -> put("channelId", channel.channelId)
                is SubscribeChannel.Name -> put("channelName", channel.channelName)
            }
            putIfNotNull("profile", request.profile)
            putIfNotNull("weight", request.weight)
            putIfNotNull("90khz", request.ninetyKhz)
            putIfNotNull("timeshiftPeriod", request.timeshiftPeriodSeconds)
            putIfNotNull("queueDepth", request.queueDepth)
        }

        is UnsubscribeRequest -> linkedMapOf("subscriptionId" to request.subscriptionId)

        is SubscriptionChangeWeightRequest -> linkedMapOf<String, Any?>("subscriptionId" to request.subscriptionId)
            .putIfNotNull("weight", request.weight)

        is SubscriptionSeekRequest -> linkedMapOf<String, Any?>(
            "subscriptionId" to request.subscriptionId,
        ).apply {
            when (val position = request.position) {
                is SubscriptionSeekPosition.Time -> put("time", position.time)
                is SubscriptionSeekPosition.Size -> put("size", position.size)
            }
            putIfNotNull("absolute", request.absolute)
        }

        is SubscriptionSkipRequest -> linkedMapOf<String, Any?>(
            "subscriptionId" to request.subscriptionId,
        ).apply {
            when (val position = request.position) {
                is SubscriptionSeekPosition.Time -> put("time", position.time)
                is SubscriptionSeekPosition.Size -> put("size", position.size)
            }
            putIfNotNull("absolute", request.absolute)
        }

        is SubscriptionSpeedRequest -> linkedMapOf(
            "subscriptionId" to request.subscriptionId,
            "speed" to request.speed,
        )

        is SubscriptionLiveRequest -> linkedMapOf("subscriptionId" to request.subscriptionId)

        is SubscriptionFilterStreamRequest -> linkedMapOf<String, Any?>("subscriptionId" to request.subscriptionId)
            .putIfNotNull("enable", request.enable)
            .putIfNotNull("disable", request.disable)

        is FileOpenRequest -> linkedMapOf("file" to request.file)

        is FileReadRequest -> linkedMapOf<String, Any?>(
            "id" to request.id,
            "size" to request.size,
        )
            .putIfNotNull("offset", request.offset)

        is FileCloseRequest -> linkedMapOf<String, Any?>("id" to request.id)
            .putIfNotNull("playposition", request.playPositionSeconds)
            .putIfNotNull("playcount", request.playCount)

        is FileStatRequest -> linkedMapOf("id" to request.id)

        is FileSeekRequest -> linkedMapOf<String, Any?>(
            "id" to request.id,
            "offset" to request.offset,
        ).putIfNotNull(
            "whence",
            request.whence?.let { whence ->
                when (whence) {
                    FileSeekWhence.SET -> "SEEK_SET"
                    FileSeekWhence.CURRENT -> "SEEK_CUR"
                    FileSeekWhence.END -> "SEEK_END"
                }
            },
        )

        else -> malformedReply()
    }

    @JvmSynthetic
    @Suppress("UNCHECKED_CAST")
    internal fun <R> decode(
        request: HtspRequest<R>,
        fields: Map<String, Any?>,
        protocolVersion: Int,
    ): R = when (request) {
        is ApiRequest -> decodeApiResponse(fields)

        is HelloRequest -> HelloResponse(
            htspVersion = fields.requiredU32("htspversion"),
            serverName = fields.observedString("servername"),
            serverVersion = fields.observedString("serverversion"),
            challenge = HtspBinary(
                fields.requiredBinary("challenge").also { challenge ->
                    if (challenge.size != 32) malformedReply()
                },
            ),
            webRoot = fields.observedString("webroot"),
            language = fields.observedString("language"),
            serverCapabilities = fields.observedStringList("servercapability"),
            apiVersion = fields.observedU32("api_version"),
        )

        is AuthenticateRequest -> AuthenticateResponse(
            noAccess = fields.observedFlag("noaccess"),
            admin = fields.observedFlag("admin"),
            streaming = fields.observedFlag("streaming"),
            dvr = fields.observedFlag("dvr"),
            failedDvr = fields.observedFlag("faileddvr"),
            anonymous = fields.observedFlag("anonymous"),
            limitAll = fields.observedU32("limitall"),
            limitDvr = fields.observedU32("limitdvr"),
            limitStreaming = fields.observedU32("limitstreaming"),
            uiLevel = fields.observedU32("uilevel"),
            uiLanguage = fields.observedString("uilanguage"),
        )

        is GetProfilesRequest -> GetProfilesResponse(fields.optionalObjectList("profiles", ::profileFromFields))

        is GetDiskSpaceRequest -> GetDiskSpaceResponse(
            freeBytes = fields.requiredS64("freediskspace"),
            usedBytes = fields.optionalS64("useddiskspace"),
            totalBytes = fields.requiredS64("totaldiskspace"),
        )

        is GetSysTimeRequest -> GetSysTimeResponse(
            // Pinned v44 source emits s32 even though the official method page says s64.
            unixTimeSeconds = fields.requiredS32("time").toLong(),
            legacyTimezoneHoursWestOfGmt = fields.requiredS32("timezone"),
            gmtOffsetMinutes = fields.optionalS32("gmtoffset"),
        )

        is EnableAsyncMetadataRequest -> HtspEmptyResponse

        is GetChannelRequest -> decodeChannel(fields, protocolVersion)

        is GetEventRequest -> GetEventResponse(eventFromFields(fields))

        is GetEventsRequest -> GetEventsResponse(fields.requiredObjectList("events", ::eventFromFields))

        is EpgQueryRequest -> decodeEpgQuery(request, fields)

        is GetEpgObjectRequest -> GetEpgObjectResponse(epgBroadcastObjectFromFields(fields))

        is GetDvrConfigsRequest -> GetDvrConfigsResponse(fields.optionalObjectList("dvrconfigs", ::dvrConfigFromFields))

        is AddDvrEntryRequest -> decodeDvrMutation(fields) { success, error ->
            val entryId = if (fields.containsKey("id")) {
                fields.optionalU32("id")
            } else {
                fields.optionalU32("dvrId")
            }
            AddDvrEntryResponse(success, entryId, error)
        }

        is UpdateDvrEntryRequest -> decodeDvrMutation(fields, ::UpdateDvrEntryResponse)

        is StopDvrEntryRequest -> decodeDvrMutation(fields, ::StopDvrEntryResponse)

        is CancelDvrEntryRequest -> decodeDvrMutation(fields, ::CancelDvrEntryResponse)

        is DeleteDvrEntryRequest -> decodeDvrMutation(fields, ::DeleteDvrEntryResponse)

        is AddAutorecEntryRequest -> decodeRecordingRuleAdd(fields, ::AddAutorecEntryResponse)

        is UpdateAutorecEntryRequest -> decodeRecordingRuleAcknowledgement(fields, UpdateAutorecEntryResponse)

        is DeleteAutorecEntryRequest -> decodeRecordingRuleAcknowledgement(fields, DeleteAutorecEntryResponse)

        is AddTimerecEntryRequest -> decodeRecordingRuleAdd(fields, ::AddTimerecEntryResponse)

        is UpdateTimerecEntryRequest -> decodeRecordingRuleAcknowledgement(fields, UpdateTimerecEntryResponse)

        is DeleteTimerecEntryRequest -> decodeRecordingRuleAcknowledgement(fields, DeleteTimerecEntryResponse)

        is GetDvrCutpointsRequest -> GetDvrCutpointsResponse(
            fields.optionalObjectList("cutpoints") { cutpoint ->
                HtspDvrCutpoint(
                    start = cutpoint.requiredU32("start"),
                    end = cutpoint.requiredU32("end"),
                    type = cutpoint.requiredU32("type"),
                )
            },
        )

        is GetTicketRequest -> GetTicketResponse(
            path = fields.requiredString("path"),
            ticket = fields.requiredString("ticket"),
        )

        is SubscribeRequest -> SubscribeResponse(
            ninetyKhz = fields.optionalU32("90khz"),
            normalizedTimestamps = fields.optionalU32("normts"),
            weight = fields.optionalU32("weight"),
            timeshiftPeriodSeconds = fields.optionalU32("timeshiftPeriod"),
        )

        is UnsubscribeRequest -> HtspEmptyResponse

        is SubscriptionChangeWeightRequest -> HtspEmptyResponse

        is SubscriptionSeekRequest -> HtspEmptyResponse

        is SubscriptionSkipRequest -> {
            if (fields.keys.any { it != "seq" }) malformedReply()
            HtspEmptyResponse
        }

        is SubscriptionSpeedRequest -> HtspEmptyResponse

        is SubscriptionLiveRequest -> HtspEmptyResponse

        is SubscriptionFilterStreamRequest -> HtspEmptyResponse

        is FileOpenRequest -> decodeFileOpen(fields)

        is FileReadRequest -> FileReadResponse(HtspBinary(fields.requiredBinary("data")))

        is FileCloseRequest -> decodeFileClose(fields)

        is FileStatRequest -> decodeFileStat(fields)

        is FileSeekRequest -> FileSeekResponse(
            offset = fields.requiredS64("offset").also { offset ->
                if (offset < 0L) malformedReply()
            },
        )

        else -> malformedReply()
    } as R

    private fun decodeChannel(fields: Map<String, Any?>, protocolVersion: Int): GetChannelResponse {
        val channelUuid = fields.optionalString("channelIdStr")
        if (protocolVersion >= 41 && channelUuid == null) malformedReply()
        val services = fields.requiredObjectList("services") { service ->
            HtspChannelService(
                name = service.requiredString("name"),
                type = service.requiredString("type"),
                content = service.requiredU32("content"),
                conditionalAccessId = service.optionalU32("caid"),
                conditionalAccessName = service.optionalString("caname"),
                providerName = service.optionalString("providername"),
            )
        }
        return GetChannelResponse(
            HtspChannel(
                channelId = fields.requiredU32("channelId"),
                channelUuid = channelUuid,
                channelNumber = fields.requiredU32("channelNumber"),
                channelNumberMinor = fields.optionalU32("channelNumberMinor"),
                channelName = fields.requiredString("channelName"),
                channelIcon = fields.optionalString("channelIcon"),
                currentEventId = fields.requiredU32("eventId"),
                nextEventId = fields.requiredU32("nextEventId"),
                services = services,
                tagIds = fields.requiredU32List("tags"),
            ),
        )
    }

    private fun decodeApiResponse(fields: Map<String, Any?>): ApiResponse {
        val permitted = setOf("seq", "noaccess", "response")
        if (fields.keys.any { it !in permitted }) malformedReply()
        if (!fields.containsKey("response")) return ApiResponse.NoPayload
        val value = fields["response"].toApiValue()
        return ApiResponse.Payload(value as? HtspApiContainer ?: malformedReply())
    }

    private fun decodeEpgQuery(
        request: EpgQueryRequest,
        fields: Map<String, Any?>,
    ): EpgQueryResponse = if (request.full == null || request.full == 0L) {
        if (fields.containsKey("events")) malformedReply()
        EpgQueryResponse.EventIds(
            if (fields.containsKey("eventIds")) fields.requiredU32List("eventIds") else emptyList(),
        )
    } else {
        if (fields.containsKey("eventIds")) malformedReply()
        EpgQueryResponse.Events(
            if (fields.containsKey("events")) {
                fields.requiredObjectList("events", ::eventFromFields)
            } else {
                emptyList()
            },
        )
    }

    private fun decodeFileStat(fields: Map<String, Any?>): FileStatResponse {
        val hasSize = fields.containsKey("size")
        val hasModifiedAt = fields.containsKey("mtime")
        if (!hasSize && !hasModifiedAt) return FileStatResponse(null, null)
        if (!hasSize || !hasModifiedAt) malformedReply()
        val sizeBytes = fields.requiredS64("size")
        if (sizeBytes < 0L) malformedReply()
        return FileStatResponse(
            sizeBytes = sizeBytes,
            modifiedAtUnixSeconds = fields.requiredS64("mtime"),
        )
    }

    private fun decodeFileOpen(fields: Map<String, Any?>): FileOpenResponse {
        val hasSize = fields.containsKey("size")
        val hasModifiedAt = fields.containsKey("mtime")
        if (hasSize != hasModifiedAt) malformedReply()
        val sizeBytes = if (hasSize) fields.requiredS64("size") else null
        if (sizeBytes != null && sizeBytes < 0L) malformedReply()
        return FileOpenResponse(
            id = fields.requiredU32("id"),
            sizeBytes = sizeBytes,
            modifiedAtUnixSeconds = if (hasModifiedAt) fields.requiredS64("mtime") else null,
        )
    }

    private fun decodeFileClose(fields: Map<String, Any?>): FileCloseResponse {
        if (fields.keys.any { it != "seq" }) malformedReply()
        return FileCloseResponse
    }

    private fun <R> decodeDvrMutation(
        fields: Map<String, Any?>,
        response: (Long?, String?) -> R,
    ): R {
        val success = fields.optionalU32("success")
        val error = fields.optionalString("error")
        if (success == null && error == null) malformedReply()
        return response(success, error)
    }

    private fun <R> decodeRecordingRuleAdd(fields: Map<String, Any?>, response: (String) -> R): R {
        fields.requireStrictSuccess()
        return response(fields.requiredString("id"))
    }

    private fun <R> decodeRecordingRuleAcknowledgement(fields: Map<String, Any?>, response: R): R {
        fields.requireStrictSuccess()
        return response
    }
}

internal typealias HtspRequestCodecs = `HtspRequestCodecs-internal`

private fun maxVersion(base: Int?, vararg selected: Int?): Int? =
    listOfNotNull(base, *selected).maxOrNull()

private fun <V> LinkedHashMap<String, Any?>.putIfNotNull(
    name: String,
    value: V?,
): LinkedHashMap<String, Any?> = apply {
    if (value != null) put(name, value)
}

private fun LinkedHashMap<String, Any?>.putRecordingRuleChannel(
    channel: HtspRecordingRuleChannel?,
): LinkedHashMap<String, Any?> = apply {
    when (channel) {
        null -> Unit
        is HtspRecordingRuleChannel.Id -> put("channelId", channel.channelId)
        HtspRecordingRuleChannel.Any -> put("channelId", -1L)
    }
}

private fun Boolean.toWireFlag(): Long = if (this) 1L else 0L

@OptIn(HtspJsonApi::class)
private fun HtspApiValue.toWireValue(): Any = when (this) {
    is HtspApiString -> value
    is HtspApiLong -> value
    is HtspApiBoolean -> value
    is HtspApiBinary -> bytes()
    is HtspApiUuid -> HtspWireUuid(bytes())
    is HtspApiObject -> LinkedHashMap<String, Any>(size).also { result ->
        forEachEntry { name, value -> result[name] = value.toWireValue() }
    }
    is HtspApiList -> ArrayList<Any>(size).also { result ->
        forEachValue { value -> result += value.toWireValue() }
    }
}

@OptIn(HtspJsonApi::class)
private fun Any?.toApiValue(): HtspApiValue = when (this) {
    is String -> HtspApiString(this)
    is Long -> HtspApiLong(this)
    is Boolean -> HtspApiBoolean(this)
    is ByteArray -> HtspApiBinary(this)
    is HtspWireUuid -> HtspApiUuid(bytes().also { if (it.size != 16) malformedReply() })
    is Map<*, *> -> {
        val result = ArrayList<Pair<String, HtspApiValue>>(size)
        forEach { (key, value) ->
            result += (key as? String ?: malformedReply()) to value.toApiValue()
        }
        HtspApiObject.create(result.toTypedArray())
    }
    is List<*> -> HtspApiList.create(map { value -> value.toApiValue() }.toTypedArray())
    else -> malformedReply()
}

private fun AddAutorecEntryRequest.validateAutorecU32Fields() {
    validateAutorecU32Fields(
        minDurationSeconds, maxDurationSeconds, fullText, mergeText, duplicateDetection,
        maximumRecordingCount, broadcastType, retentionDays, removalDays, priority, daysOfWeekMask,
    )
}

private fun UpdateAutorecEntryRequest.validateAutorecU32Fields() {
    validateAutorecU32Fields(
        minDurationSeconds, maxDurationSeconds, fullText, mergeText, duplicateDetection,
        maximumRecordingCount, broadcastType, retentionDays, removalDays, priority, daysOfWeekMask,
    )
}

private fun validateAutorecU32Fields(
    minDurationSeconds: Long?,
    maxDurationSeconds: Long?,
    fullText: Long?,
    mergeText: Long?,
    duplicateDetection: Long?,
    maximumRecordingCount: Long?,
    broadcastType: Long?,
    retentionDays: Long?,
    removalDays: Long?,
    priority: Long?,
    daysOfWeekMask: Long?,
) {
    minDurationSeconds?.let { requireU32("minduration", it) }
    maxDurationSeconds?.let { requireU32("maxduration", it) }
    fullText?.let { requireU32("fulltext", it) }
    mergeText?.let { requireU32("mergetext", it) }
    duplicateDetection?.let { requireU32("dupDetect", it) }
    maximumRecordingCount?.let { requireU32("maxCount", it) }
    broadcastType?.let { requireU32("broadcastType", it) }
    retentionDays?.let { requireU32("retention", it) }
    removalDays?.let { requireU32("removal", it) }
    priority?.let { requireU32("priority", it) }
    daysOfWeekMask?.let { requireU32("daysOfWeek", it) }
}

private fun AddTimerecEntryRequest.validateTimerecU32Fields() {
    validateTimerecU32Fields(
        startMinutesSinceMidnight, stopMinutesSinceMidnight, retentionDays, removalDays, priority, daysOfWeekMask,
    )
}

private fun UpdateTimerecEntryRequest.validateTimerecU32Fields() {
    validateTimerecU32Fields(
        startMinutesSinceMidnight, stopMinutesSinceMidnight, retentionDays, removalDays, priority, daysOfWeekMask,
    )
}

private fun validateTimerecU32Fields(
    startMinutesSinceMidnight: Long?,
    stopMinutesSinceMidnight: Long?,
    retentionDays: Long?,
    removalDays: Long?,
    priority: Long?,
    daysOfWeekMask: Long?,
) {
    startMinutesSinceMidnight?.let { requireU32("start", it) }
    stopMinutesSinceMidnight?.let { requireU32("stop", it) }
    retentionDays?.let { requireU32("retention", it) }
    removalDays?.let { requireU32("removal", it) }
    priority?.let { requireU32("priority", it) }
    daysOfWeekMask?.let { requireU32("daysOfWeek", it) }
}

private fun Map<*, *>.requireStrictSuccess() {
    if (requiredU32("success") != 1L) malformedReply()
}

private fun Map<*, *>.requiredS64(name: String): Long =
    this[name] as? Long ?: malformedReply()

private fun Map<*, *>.optionalS64(name: String): Long? =
    if (containsKey(name)) requiredS64(name) else null

private fun Map<*, *>.requiredS32(name: String): Int {
    val value = requiredS64(name)
    if (value !in Int.MIN_VALUE.toLong()..Int.MAX_VALUE.toLong()) malformedReply()
    return value.toInt()
}

private fun Map<*, *>.optionalS32(name: String): Int? =
    if (containsKey(name)) requiredS32(name) else null

private fun Map<*, *>.requiredU32(name: String): Long {
    val value = requiredS64(name)
    if (value !in 0L..HTSP_U32_MAX) malformedReply()
    return value
}

private fun Map<*, *>.optionalU32(name: String): Long? =
    if (containsKey(name)) requiredU32(name) else null

private fun Map<*, *>.requiredString(name: String): String =
    this[name] as? String ?: malformedReply()

private fun Map<*, *>.requiredBinary(name: String): ByteArray =
    this[name] as? ByteArray ?: malformedReply()

private fun Map<*, *>.optionalString(name: String): String? =
    if (containsKey(name)) requiredString(name) else null

private fun Map<*, *>.observedString(name: String): String? = this[name] as? String

private fun Map<*, *>.observedU32(name: String): Long? =
    (this[name] as? Long)?.takeIf { it in 0L..HTSP_U32_MAX }

private fun Map<*, *>.observedFlag(name: String): Boolean? = when (this[name]) {
    0L -> false
    1L -> true
    else -> null
}

private fun Map<*, *>.observedStringList(name: String): List<String>? {
    val source = this[name] as? List<*> ?: return null
    if (source.any { it !is String }) return null
    return source.map { it as String }.immutableSnapshot()
}

private fun Map<*, *>.requiredU32List(name: String): List<Long> {
    val source = this[name] as? List<*> ?: malformedReply()
    return source.map { value ->
        val decoded = value as? Long ?: malformedReply()
        if (decoded !in 0L..HTSP_U32_MAX) malformedReply()
        decoded
    }.immutableSnapshot()
}

private fun <R> Map<*, *>.requiredObjectList(
    name: String,
    mapper: (Map<*, *>) -> R,
): List<R> {
    val source = this[name] as? List<*> ?: malformedReply()
    return source.map { value -> mapper(value as? Map<*, *> ?: malformedReply()) }
        .immutableSnapshot()
}

private fun <R> Map<*, *>.optionalObjectList(
    name: String,
    mapper: (Map<*, *>) -> R,
): List<R>? = if (containsKey(name)) requiredObjectList(name, mapper) else null

private fun profileFromFields(fields: Map<*, *>): HtspProfile = HtspProfile(
    profileUuid = fields.requiredString("uuid"),
    name = fields.requiredString("name"),
    comment = fields.requiredString("comment"),
)

private fun dvrConfigFromFields(fields: Map<*, *>): HtspDvrConfig = HtspDvrConfig(
    dvrConfigUuid = fields.requiredString("uuid"),
    name = fields.requiredString("name"),
    comment = fields.requiredString("comment"),
)

private fun eventFromFields(fields: Map<*, *>): HtspEvent = HtspEvent(
    eventId = fields.requiredU32("eventId"),
    channelId = fields.optionalU32("channelId"),
    start = fields.requiredS64("start"),
    stop = fields.requiredS64("stop"),
    title = fields.optionalString("title"),
    subtitle = fields.optionalString("subtitle"),
    summary = fields.optionalString("summary"),
    description = fields.optionalString("description"),
    categories = fields.optionalStringList("category"),
    keywords = fields.optionalStringList("keyword"),
    seriesLinkUri = fields.optionalString("serieslinkUri"),
    episodeUri = fields.optionalString("episodeUri"),
    contentType = fields.optionalU32("contentType"),
    ageRating = fields.optionalU32("ageRating"),
    ratingLabel = fields.optionalString("ratingLabel"),
    ratingIcon = fields.optionalString("ratingIcon"),
    ratingAuthority = fields.optionalString("ratingAuthority"),
    ratingCountry = fields.optionalString("ratingCountry"),
    starRating = fields.optionalU32("starRating"),
    copyrightYear = fields.optionalU32("copyrightYear"),
    firstAired = fields.optionalS64("firstAired"),
    isNew = fields.optionalU32("isNew"),
    seasonNumber = fields.optionalU32("seasonNumber"),
    seasonCount = fields.optionalU32("seasonCount"),
    episodeNumber = fields.optionalU32("episodeNumber"),
    episodeCount = fields.optionalU32("episodeCount"),
    partNumber = fields.optionalU32("partNumber"),
    partCount = fields.optionalU32("partCount"),
    episodeOnscreen = fields.optionalString("episodeOnscreen"),
    image = fields.optionalString("image"),
    dvrId = fields.optionalU32("dvrId"),
    nextEventId = fields.optionalU32("nextEventId"),
)

private fun epgBroadcastObjectFromFields(fields: Map<*, *>): HtspEpgBroadcastObject {
    if (fields.requiredU32("tp") != 1L) malformedReply()
    return HtspEpgBroadcastObject(
        id = fields.requiredU32("id"),
        updatedUnixSeconds = fields.requiredS64("up"),
        startUnixSeconds = fields.requiredS64("start"),
        stopUnixSeconds = fields.requiredS64("stop"),
        grabber = fields.optionalString("gr"),
        channelUuid = fields.optionalString("ch"),
        eventId = fields.optionalU32("eid"),
        externalEventId = fields.optionalString("xeid"),
        widescreen = fields.optionalTrueFlag("is_wd"),
        highDefinition = fields.optionalTrueFlag("is_hd"),
        blackAndWhite = fields.optionalTrueFlag("is_bw"),
        deafSigned = fields.optionalTrueFlag("is_de"),
        subtitled = fields.optionalTrueFlag("is_st"),
        audioDescribed = fields.optionalTrueFlag("is_ad"),
        isNew = fields.optionalTrueFlag("is_n"),
        isRepeat = fields.optionalTrueFlag("is_r"),
        lines = fields.optionalU32("lines"),
        aspectRatio = fields.optionalU32("aspect"),
        starRating = fields.optionalU32("star"),
        ageRating = fields.optionalU32("age"),
        ratingLabel = fields.optionalString("ratlab"),
        image = fields.optionalString("img"),
        titles = fields.optionalStringMap("tit"),
        subtitles = fields.optionalStringMap("sti"),
        summaries = fields.optionalStringMap("sum"),
        descriptions = fields.optionalStringMap("des"),
        episodeNumber = fields.optionalEpgEpisodeNumber("epn"),
        genres = fields.optionalU32List("genre"),
        copyrightYear = fields.optionalU32("cyear"),
        firstAiredUnixSeconds = fields.optionalS64("fair"),
        categories = fields.optionalSortedUniqueStringList("cat"),
        keywords = fields.optionalSortedUniqueStringList("key"),
        seriesLinkUri = fields.optionalString("slink"),
        episodeLinkUri = fields.optionalString("elink"),
    )
}

private fun Map<*, *>.optionalTrueFlag(name: String): Boolean {
    if (!containsKey(name)) return false
    if (requiredU32(name) != 1L) malformedReply()
    return true
}

private fun Map<*, *>.optionalStringMap(name: String): Map<String, String>? {
    if (!containsKey(name)) return null
    val source = this[name] as? Map<*, *> ?: malformedReply()
    val result = LinkedHashMap<String, String>(source.size)
    source.forEach { (key, value) ->
        result[key as? String ?: malformedReply()] = value as? String ?: malformedReply()
    }
    return Collections.unmodifiableMap(result)
}

private fun Map<*, *>.optionalEpgEpisodeNumber(name: String): HtspEpgEpisodeNumber? {
    if (!containsKey(name)) return null
    val source = this[name] as? Map<*, *> ?: malformedReply()
    val result = HtspEpgEpisodeNumber(
        episodeNumber = source.optionalU32("enum"),
        episodeCount = source.optionalU32("ecnt"),
        seasonNumber = source.optionalU32("snum"),
        seasonCount = source.optionalU32("scnt"),
        partNumber = source.optionalU32("pnum"),
        partCount = source.optionalU32("pcnt"),
        text = source.optionalString("text"),
    )
    if (result == HtspEpgEpisodeNumber(null, null, null, null, null, null, null)) malformedReply()
    return result
}

private fun Map<*, *>.optionalU32List(name: String): List<Long>? =
    if (containsKey(name)) requiredU32List(name) else null

private fun Map<*, *>.optionalSortedUniqueStringList(name: String): List<String>? {
    val values = optionalStringList(name) ?: return null
    if (values.zipWithNext().any { (previous, next) -> compareUtf8(previous, next) >= 0 }) malformedReply()
    return values
}

private fun compareUtf8(left: String, right: String): Int {
    val leftBytes = left.toByteArray(Charsets.UTF_8)
    val rightBytes = right.toByteArray(Charsets.UTF_8)
    for (index in 0 until minOf(leftBytes.size, rightBytes.size)) {
        val difference = (leftBytes[index].toInt() and 0xff) - (rightBytes[index].toInt() and 0xff)
        if (difference != 0) return difference
    }
    return leftBytes.size - rightBytes.size
}

private fun Map<*, *>.optionalStringList(name: String): List<String>? {
    if (!containsKey(name)) return null
    val source = this[name] as? List<*> ?: malformedReply()
    return source.map { value -> value as? String ?: malformedReply() }.immutableSnapshot()
}

private fun malformedReply(): Nothing = throw HtspProtocolMappingException()
