#!/usr/bin/env python3
"""Generate the reviewed 30-message finite HTSP server-message dispatch."""

from __future__ import annotations

import argparse
import sys
import tempfile
from dataclasses import replace
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from htsp_surface import (
    GENERATED_OUTPUT_BY_KEY,
    SERVER_MESSAGE_CATALOG,
    self_test_generated_output_metadata,
    validate_generated_output_metadata,
)

OUTPUT_METADATA = GENERATED_OUTPUT_BY_KEY["server-dispatch"]
OUTPUT = SCRIPT_DIR.parents[1] / OUTPUT_METADATA.relative_path


CATALOG = SERVER_MESSAGE_CATALOG

EXPECTED_METHODS = tuple(entry.method for entry in CATALOG)
def validate_catalog(catalog=CATALOG) -> None:
    validate_generated_output_metadata()
    methods = tuple(entry.method for entry in catalog)
    if methods != EXPECTED_METHODS or len(methods) != 30 or len(set(methods)) != 30:
        raise ValueError("typed server-message catalog must contain exactly the reviewed 30 methods")
    types = tuple(entry.message_type for entry in catalog)
    decoders = tuple(entry.decoder for entry in catalog)
    if len(set(types)) != 30 or len(set(decoders)) != 30:
        raise ValueError("typed server-message types and decoders must be one-to-one")


def render(catalog=CATALOG) -> str:
    validate_catalog(catalog)
    lines = [
        "// Generated by docs/htsp-protocol/generate_typed_server_messages.py. DO NOT EDIT.",
        "// docs/htsp-protocol/htsp_surface.py is the reviewed finite dispatch authority.",
        f"package {OUTPUT_METADATA.package}",
        "",
        "private data class TypedHtspServerMessageCatalogEntry(",
        "    val method: String,",
        "    val messageType: String,",
        "    val minimumProtocolVersion: Int?,",
        ")",
        "",
        "private val typedHtspServerMessageCatalog: List<TypedHtspServerMessageCatalogEntry> = listOf(",
    ]
    for entry in catalog:
        version = "null" if entry.minimum_version is None else str(entry.minimum_version)
        lines.append(
            f'    TypedHtspServerMessageCatalogEntry("{entry.method}", '
            f'"{entry.message_type}", {version}),'
        )
    lines.extend(
        (
            ")",
            "",
            "public sealed interface HtspServerMessageDecodeResult",
            "public data class HtspServerMessageDecoded(",
            "    public val message: HtspServerMessage,",
            ") : HtspServerMessageDecodeResult",
            "public data object HtspServerMessageUnknownMethod : HtspServerMessageDecodeResult",
            "public data object HtspServerMessageMalformedKnownMessage : HtspServerMessageDecodeResult",
            "",
            "public fun decodeHtspServerMessage(fields: Map<String, Any?>): HtspServerMessageDecodeResult {",
            "    if (fields.containsKey(\"seq\")) return HtspServerMessageUnknownMethod",
            "    val method = fields[\"method\"] as? String",
            "        ?: return HtspServerMessageUnknownMethod",
            "    return when (method) {",
        )
    )
    for entry in catalog:
        lines.append(
            f'        "{entry.method}" -> decodeKnownServerMessage {{ {entry.decoder}(fields) }}'
        )
    lines.extend(
        (
            "        else -> HtspServerMessageUnknownMethod",
            "    }",
            "}",
            "",
            "private fun decodeKnownServerMessage(block: () -> HtspServerMessage): HtspServerMessageDecodeResult =",
            "    try {",
            "        HtspServerMessageDecoded(block())",
            "    } catch (_: IllegalArgumentException) {",
            "        HtspServerMessageMalformedKnownMessage",
            "    }",
            "",
            "@JvmSynthetic",
            "internal fun typedHtspServerMessageCatalogForTest(): List<Pair<String, String>> =",
            "    typedHtspServerMessageCatalog.map { it.method to it.messageType }",
            "",
        )
    )
    return "\n".join(lines)


def self_test() -> None:
    self_test_generated_output_metadata()
    validate_catalog()
    first = render()
    if first != render():
        raise AssertionError("generator output is not deterministic")
    if first.count(" -> decodeKnownServerMessage {") != 30:
        raise AssertionError("generated dispatch must contain exactly 30 finite branches")
    public_declarations = (
        "public sealed interface HtspServerMessageDecodeResult",
        "public data class HtspServerMessageDecoded(",
        "public data object HtspServerMessageUnknownMethod",
        "public data object HtspServerMessageMalformedKnownMessage",
    )
    for declaration in public_declarations:
        if declaration not in first:
            raise AssertionError(f"generated dispatch lacks declaration: {declaration}")
    if "public fun decodeHtspServerMessage(" not in first:
        raise AssertionError("generated dispatch lacks the public decoder entry point")
    for forbidden in ("internal typealias", "@JvmSynthetic\ninternal fun decodeHtspServerMessage"):
        if forbidden in first:
            raise AssertionError(f"generated dispatch retains hidden decoder vocabulary: {forbidden}")
    mutations = (
        CATALOG[:-1],
        CATALOG + (CATALOG[0],),
        (replace(CATALOG[0], method=CATALOG[1].method),) + CATALOG[1:],
        (replace(CATALOG[0], message_type=CATALOG[1].message_type),) + CATALOG[1:],
        (replace(CATALOG[0], decoder=CATALOG[1].decoder),) + CATALOG[1:],
    )
    for mutation in mutations:
        try:
            validate_catalog(mutation)
        except ValueError:
            pass
        else:
            raise AssertionError("catalog mutation was not rejected")
    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "generated.kt"
        path.write_text(first, encoding="utf-8")
        if path.read_text(encoding="utf-8") != first:
            raise AssertionError("temporary output round-trip drifted")


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    validate_catalog()
    if args.self_test:
        self_test()
        return 0
    generated = render()
    if args.write:
        OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
        return 0
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
        raise SystemExit(f"generated typed HTSP server-message source is stale: {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
