#!/usr/bin/env python3
"""Generate the reviewed 39-request HTSP convenience/catalog surface."""

from __future__ import annotations

import argparse
import sys
import tempfile
from dataclasses import replace as dataclass_replace
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from htsp_surface import CATALOG, SELECTOR_OVERLOADS, Entry, Parameter, SelectorOverload, parameter

OUTPUT = (
    SCRIPT_DIR.parents[1]
    / "sdk/htsp-protocol/src/main/kotlin/at/bernhardberger/tvheadend/htsp/GeneratedHtspExtensions.kt"
)


def render_extension(
    entry: Entry,
    parameters: tuple[Parameter, ...],
    request_arguments: tuple[str, ...],
    function_name: str | None = None,
) -> list[str]:
    lines = (["@HtspJsonApi"] if entry.method == "api" else []) + [
        f"public suspend fun HtspConnection.{function_name or entry.method}("
    ]
    for value in parameters:
        default = "" if value.default is None else f" = {value.default}"
        lines.append(f"    {value.name}: {value.type}{default},")
    lines.extend((
        "    timeoutMs: Long = 5_000L,",
        "    expectedGeneration: HtspConnectionGeneration? = null,",
        f"): HtspResult<{entry.response}> =",
        "    execute(",
    ))
    if request_arguments:
        lines.append(f"        request = {entry.request}(")
        lines.extend(f"            {argument}," for argument in request_arguments)
        lines.append("        ),")
    else:
        lines.append(f"        request = {entry.request}(),")
    lines.extend((
        "        timeoutMs = timeoutMs,",
        "        expectedGeneration = expectedGeneration,",
        "    )",
        "",
    ))
    return lines


def project_constructor_parameters(
    entry: Entry,
    parameter_names: tuple[str, ...],
    *,
    strip_defaults: bool = False,
) -> tuple[Parameter, ...]:
    if not parameter_names or len(parameter_names) != len(set(parameter_names)):
        raise ValueError(f"{entry.method}: constructor projection must contain unique parameter names")
    by_name = {value.name: value for value in entry.parameters}
    if len(by_name) != len(entry.parameters):
        raise ValueError(f"{entry.method}: constructor parameter names must be unique")
    try:
        projected = tuple(by_name[name] for name in parameter_names)
    except KeyError as error:
        raise ValueError(f"{entry.method}: projection references unknown constructor parameter {error.args[0]}") from error
    if strip_defaults:
        projected = tuple(dataclass_replace(value, default=None) for value in projected)
    return projected


def extension_parameters(entry: Entry) -> tuple[Parameter, ...]:
    projection = entry.canonical_extension_projection
    return entry.parameters if projection is None else project_constructor_parameters(entry, projection)


def overload_parameters(
    entry: Entry,
    overload: SelectorOverload,
) -> tuple[tuple[Parameter, ...], tuple[str, ...]]:
    if overload.parameter_projection:
        if overload.parameters or overload.request_arguments:
            raise ValueError(f"{entry.method}: projected overload must derive parameters and request arguments")
        parameters = project_constructor_parameters(
            entry,
            overload.parameter_projection,
            strip_defaults=overload.strip_projection_defaults,
        )
        return parameters, tuple(f"{value.name} = {value.name}" for value in parameters)
    if overload.strip_projection_defaults:
        raise ValueError(f"{entry.method}: default stripping requires a constructor projection")
    return overload.parameters, overload.request_arguments


def render() -> str:
    lines = [
        "// Generated by docs/htsp-protocol/generate_typed_requests.py. DO NOT EDIT.",
        "// The reviewed catalog in that generator is the request/response constructor authority.",
        "package at.bernhardberger.tvheadend.htsp",
        "",
        "internal data class `TypedHtspRequestCatalogEntry-internal`(",
        "    val method: String,",
        "    val requestType: String,",
        "    val responseType: String,",
        "    val access: HtspAccess,",
        "    val minimumProtocolVersion: Int?,",
        ")",
        "",
        "internal typealias TypedHtspRequestCatalogEntry =",
        "    `TypedHtspRequestCatalogEntry-internal`",
        "",
        "@get:JvmSynthetic",
        "internal val typedHtspRequestCatalog: List<TypedHtspRequestCatalogEntry> = listOf(",
    ]
    for entry in CATALOG:
        version = "null" if entry.minimum_version is None else str(entry.minimum_version)
        lines.append(
            f'    TypedHtspRequestCatalogEntry("{entry.method}", "{entry.request}", '
            f'"{entry.response}", HtspAccess.{entry.access}, {version}),'
        )
    lines.extend((")", ""))
    for entry in CATALOG:
        parameters = extension_parameters(entry)
        request_arguments = tuple(f"{value.name} = {value.name}" for value in parameters)
        lines.extend(render_extension(entry, parameters, request_arguments))
        for overload in SELECTOR_OVERLOADS:
            if overload.method == entry.method:
                parameters, request_arguments = overload_parameters(entry, overload)
                lines.extend(
                    render_extension(
                        entry,
                        parameters,
                        request_arguments,
                        overload.function_name,
                    )
                )
    return "\n".join(lines)


def validate_file_close_projections(
    catalog: tuple[Entry, ...],
    overloads: tuple[SelectorOverload, ...],
) -> None:
    matching_entries = tuple(entry for entry in catalog if entry.method == "fileClose")
    if len(matching_entries) != 1:
        raise ValueError("catalog must contain exactly one fileClose entry")
    entry = matching_entries[0]
    if entry.canonical_extension_projection != ("id",):
        raise ValueError("canonical fileClose must be an explicit id-only constructor projection")
    if len(entry.parameters) != 3 or tuple(value.name for value in entry.parameters[:1]) != entry.canonical_extension_projection:
        raise ValueError("FileCloseRequest must retain one id plus two progress constructor parameters")
    if entry.parameters[0].default is not None or any(value.default != "null" for value in entry.parameters[1:]):
        raise ValueError("FileCloseRequest must retain its required id and optional progress defaults")
    if extension_parameters(entry) != (entry.parameters[0],):
        raise ValueError("canonical fileClose projection drifted from FileCloseRequest")
    matching = tuple(
        overload for overload in overloads
        if overload.function_name == "fileCloseWithProgress"
    )
    if len(matching) != 1:
        raise ValueError("fileCloseWithProgress must preserve its exact reviewed constructor projection")
    overload = matching[0]
    if (
        overload.method != entry.method
        or overload.parameters
        or overload.request_arguments
        or overload.parameter_projection != tuple(value.name for value in entry.parameters)
        or not overload.strip_projection_defaults
    ):
        raise ValueError("fileCloseWithProgress must derive its required parameters from FileCloseRequest")
    parameters, arguments = overload_parameters(entry, overload)
    if parameters != tuple(dataclass_replace(value, default=None) for value in entry.parameters):
        raise ValueError("fileCloseWithProgress parameters must derive from the full constructor without defaults")
    if arguments != tuple(f"{value.name} = {value.name}" for value in entry.parameters):
        raise ValueError("fileCloseWithProgress request arguments must derive from the full constructor")


def validate_catalog() -> None:
    expected = (
        "getProfiles", "getDiskSpace", "getSysTime", "enableAsyncMetadata", "getChannel", "getEvent",
        "getEvents", "epgQuery", "getEpgObject", "getDvrConfigs", "addDvrEntry", "updateDvrEntry", "stopDvrEntry",
        "cancelDvrEntry", "deleteDvrEntry", "addAutorecEntry", "updateAutorecEntry",
        "deleteAutorecEntry", "addTimerecEntry", "updateTimerecEntry", "deleteTimerecEntry",
        "getDvrCutpoints", "getTicket", "subscribe", "unsubscribe",
        "subscriptionChangeWeight", "subscriptionSeek", "subscriptionSkip", "subscriptionSpeed",
        "subscriptionLive", "subscriptionFilterStream", "fileOpen", "fileRead", "fileClose",
        "fileStat", "fileSeek", "api", "hello", "authenticate",
    )
    methods = tuple(entry.method for entry in CATALOG)
    if methods != expected or len(set(methods)) != 39:
        raise ValueError("typed request catalog must contain exactly the reviewed 39 methods")
    epg_query = CATALOG[7]
    if epg_query != Entry(
        "epgQuery", "EpgQueryRequest", "EpgQueryResponse", "ACCESS_HTSP_STREAMING", 4, (
            parameter("query", "String"),
            parameter("channelId", "Long?", "null"),
            parameter("tagId", "Long?", "null"),
            parameter("contentType", "Long?", "null"),
            parameter("language", "String?", "null"),
            parameter("fullText", "Boolean?", "null"),
            parameter("mergeText", "Boolean?", "null"),
            parameter("full", "Long?", "null"),
            parameter("minDurationSeconds", "Long?", "null"),
            parameter("maxDurationSeconds", "Long?", "null"),
        ),
    ):
        raise ValueError("epgQuery catalog entry must preserve the reviewed constructor contract")
    get_epg_object = CATALOG[8]
    if get_epg_object != Entry(
        "getEpgObject", "GetEpgObjectRequest", "GetEpgObjectResponse", "ACCESS_HTSP_STREAMING", None, (
            parameter("id", "Long"),
            parameter("objectType", "HtspEpgObjectType?", "HtspEpgObjectType.BROADCAST"),
        ),
    ):
        raise ValueError("getEpgObject catalog entry must preserve the reviewed constructor contract")
    get_ticket = CATALOG[22]
    if get_ticket != Entry(
        "getTicket", "GetTicketRequest", "GetTicketResponse", "ACCESS_HTSP_STREAMING", 5, (
            parameter("selector", "GetTicketSelector"),
        ),
    ):
        raise ValueError("getTicket catalog entry must preserve the reviewed constructor contract")
    subscription_skip = CATALOG[27]
    if subscription_skip != Entry(
        "subscriptionSkip", "SubscriptionSkipRequest", "HtspEmptyResponse", "ACCESS_HTSP_STREAMING", 9, (
            parameter("subscriptionId", "Long"),
            parameter("position", "SubscriptionSeekPosition"),
            parameter("absolute", "Long?", "null"),
        ),
    ):
        raise ValueError("subscriptionSkip catalog entry must preserve the reviewed constructor contract")
    file_operations = CATALOG[31:36]
    if (*file_operations[:2], *file_operations[3:]) != (
        Entry("fileOpen", "FileOpenRequest", "FileOpenResponse", "ACCESS_HTSP_RECORDER", 8, (
            parameter("file", "String"),
        )),
        Entry("fileRead", "FileReadRequest", "FileReadResponse", "ACCESS_HTSP_RECORDER", 8, (
            parameter("id", "Long"),
            parameter("size", "Long"),
            parameter("offset", "Long?", "null"),
        )),
        Entry("fileStat", "FileStatRequest", "FileStatResponse", "ACCESS_HTSP_RECORDER", 8, (
            parameter("id", "Long"),
        )),
        Entry("fileSeek", "FileSeekRequest", "FileSeekResponse", "ACCESS_HTSP_RECORDER", 8, (
            parameter("id", "Long"),
            parameter("offset", "Long"),
            parameter("whence", "FileSeekWhence?", "null"),
        )),
    ):
        raise ValueError("file operation catalog entries must preserve the reviewed constructor contract")
    file_close = file_operations[2]
    if (
        file_close.method,
        file_close.request,
        file_close.response,
        file_close.access,
        file_close.minimum_version,
    ) != ("fileClose", "FileCloseRequest", "FileCloseResponse", "ACCESS_HTSP_RECORDER", 8):
        raise ValueError("fileClose catalog identity must preserve the reviewed contract")
    api_bridge = CATALOG[36]
    if api_bridge != Entry("api", "ApiRequest", "ApiResponse", "ACCESS_ANONYMOUS", 24, (
        parameter("path", "String"),
        parameter("args", "HtspApiObject?", "null"),
    )):
        raise ValueError("api catalog entry must preserve the reviewed constructor contract")
    handshake = CATALOG[37:39]
    if handshake != (
        Entry("hello", "HelloRequest", "HelloResponse", "ACCESS_ANONYMOUS", None, (
            parameter("htspVersion", "Long"),
            parameter("clientName", "String"),
        )),
        Entry("authenticate", "AuthenticateRequest", "AuthenticateResponse", "ACCESS_ANONYMOUS", None),
    ):
        raise ValueError("handshake catalog entries must preserve the reviewed constructor contract")
    if tuple((overload.method, overload.function_name) for overload in SELECTOR_OVERLOADS) != (
        ("addDvrEntry", None), ("addDvrEntry", None), ("subscribe", None), ("subscribe", None),
        ("subscriptionSeek", None), ("subscriptionSeek", None),
        ("subscriptionSkip", None), ("subscriptionSkip", None),
        ("getTicket", None), ("getTicket", None), ("fileClose", "fileCloseWithProgress"),
    ):
        raise ValueError("typed request overload catalog must contain exactly eleven reviewed cases")
    validate_file_close_projections(CATALOG, SELECTOR_OVERLOADS)


def self_test() -> None:
    validate_catalog()
    try:
        validate_file_close_projections(
            tuple(
                dataclass_replace(entry, canonical_extension_projection=None)
                if entry.method == "fileClose" else entry
                for entry in CATALOG
            ),
            SELECTOR_OVERLOADS,
        )
    except ValueError:
        pass
    else:
        raise AssertionError("fileClose canonical projection mutation was accepted")
    file_close_progress = SELECTOR_OVERLOADS[-1]
    invalid_file_close_progress_catalogs = (
        SELECTOR_OVERLOADS[:-1] + (
            dataclass_replace(
                file_close_progress,
                parameter_projection=("id", "playCount", "playPositionSeconds"),
            ),
        ),
        SELECTOR_OVERLOADS[:-1] + (
            dataclass_replace(
                file_close_progress,
                parameter_projection=("id", "playPositionSeconds"),
            ),
        ),
        SELECTOR_OVERLOADS[:-1] + (
            dataclass_replace(
                file_close_progress,
                parameter_projection=("id", "playPositionSeconds", "playPositionSeconds", "playCount"),
            ),
        ),
        SELECTOR_OVERLOADS[:-1] + (
            dataclass_replace(
                file_close_progress,
                parameter_projection=("id", "playPosition", "playCount"),
            ),
        ),
        SELECTOR_OVERLOADS[:-1] + (
            dataclass_replace(
                file_close_progress,
                strip_projection_defaults=False,
            ),
        ),
        SELECTOR_OVERLOADS[:-1] + (
            dataclass_replace(file_close_progress, parameters=(parameter("id", "Long"),)),
        ),
        SELECTOR_OVERLOADS[:-1] + (
            dataclass_replace(file_close_progress, request_arguments=("id = id",)),
        ),
        SELECTOR_OVERLOADS[:-1] + (dataclass_replace(file_close_progress, method="fileRead"),),
        SELECTOR_OVERLOADS[:-1] + (
            dataclass_replace(file_close_progress, function_name="fileCloseProgress"),
        ),
    )
    for invalid_overloads in invalid_file_close_progress_catalogs:
        try:
            validate_file_close_projections(CATALOG, invalid_overloads)
        except ValueError:
            pass
        else:
            raise AssertionError("fileCloseWithProgress mapping mutation was accepted")
    first = render()
    second = render()
    if first != second:
        raise AssertionError("generator output is not deterministic")
    extension_lines = [line for line in first.splitlines() if line.startswith("public suspend fun")]
    if len(extension_lines) != 50:
        raise AssertionError("generated extensions must contain 39 canonical and 11 reviewed overloads")
    if "    request:" in first:
        raise AssertionError("generated extensions must not accept request objects")
    if first.count("timeoutMs: Long = 5_000L") != 50:
        raise AssertionError("every generated extension must expose the default request timeout")
    if first.count("expectedGeneration: HtspConnectionGeneration? = null") != 50:
        raise AssertionError("every generated extension must expose the optional generation fence")
    required_signatures = (
        "public suspend fun HtspConnection.getEvents(\n    channelId: Long? = null,",
        "public suspend fun HtspConnection.epgQuery(\n    query: String,\n    channelId: Long? = null,",
        "public suspend fun HtspConnection.getEpgObject(\n    id: Long,\n    objectType: HtspEpgObjectType? = HtspEpgObjectType.BROADCAST,",
        "public suspend fun HtspConnection.getTicket(\n    selector: GetTicketSelector,",
        "public suspend fun HtspConnection.getTicket(\n    selector: GetTicketSelector.Channel,",
        "public suspend fun HtspConnection.getTicket(\n    selector: GetTicketSelector.Dvr,",
        "public suspend fun HtspConnection.fileStat(\n    id: Long,",
        "public suspend fun HtspConnection.fileOpen(\n    file: String,",
        "public suspend fun HtspConnection.fileRead(\n    id: Long,\n    size: Long,\n    offset: Long? = null,",
        "public suspend fun HtspConnection.fileClose(\n    id: Long,",
        "public suspend fun HtspConnection.fileCloseWithProgress(\n    id: Long,\n    playPositionSeconds: Long?,\n    playCount: Long?,",
        "public suspend fun HtspConnection.fileSeek(\n    id: Long,\n    offset: Long,\n    whence: FileSeekWhence? = null,",
        "@HtspJsonApi\npublic suspend fun HtspConnection.api(\n    path: String,\n    args: HtspApiObject? = null,",
        "    fullText: Boolean? = null,\n    mergeText: Boolean? = null,\n    full: Long? = null,\n    minDurationSeconds: Long? = null,\n    maxDurationSeconds: Long? = null,",
        "public suspend fun HtspConnection.addDvrEntry(\n    selector: AddDvrEntrySelector,",
        "    selector: AddDvrEntrySelector,\n    configName: String? = null,\n    language: String? = null,\n    title: String? = null,",
        "public suspend fun HtspConnection.addDvrEntry(\n    eventId: Long,",
        "public suspend fun HtspConnection.addDvrEntry(\n    channelId: Long,\n    start: Long,\n    stop: Long,",
        "public suspend fun HtspConnection.subscribe(\n    subscriptionId: Long,\n    channel: SubscribeChannel,",
        "    channel: SubscribeChannel,\n    profile: String? = null,\n    weight: Long? = null,\n    ninetyKhz: Long? = null,\n    timeshiftPeriodSeconds: Long? = null,\n    queueDepth: Long? = null,",
        "public suspend fun HtspConnection.subscribe(\n    subscriptionId: Long,\n    channelId: Long,",
        "public suspend fun HtspConnection.subscribe(\n    subscriptionId: Long,\n    channelName: String,",
        "public suspend fun HtspConnection.subscriptionSeek(\n    subscriptionId: Long,\n    position: SubscriptionSeekPosition,",
        "public suspend fun HtspConnection.subscriptionSeek(\n    subscriptionId: Long,\n    position: SubscriptionSeekPosition.Time,",
        "public suspend fun HtspConnection.subscriptionSeek(\n    subscriptionId: Long,\n    position: SubscriptionSeekPosition.Size,",
        "public suspend fun HtspConnection.subscriptionSkip(\n    subscriptionId: Long,\n    position: SubscriptionSeekPosition,",
        "public suspend fun HtspConnection.subscriptionSkip(\n    subscriptionId: Long,\n    position: SubscriptionSeekPosition.Time,",
        "public suspend fun HtspConnection.subscriptionSkip(\n    subscriptionId: Long,\n    position: SubscriptionSeekPosition.Size,",
        "public suspend fun HtspConnection.updateDvrEntry(\n    entryId: Long,\n    channelId: Long? = null,\n    configName: String? = null,\n    title: String? = null,",
        "    comment: String? = null,\n    playCount: Long? = null,\n    playPosition: Long? = null,\n    enabled: Long? = null,\n    start: Long? = null,",
        "public suspend fun HtspConnection.addAutorecEntry(\n    title: String,\n    channel: HtspRecordingRuleChannel? = null,",
        "public suspend fun HtspConnection.updateAutorecEntry(\n    id: String,\n    channel: HtspRecordingRuleChannel? = null,",
        "public suspend fun HtspConnection.deleteAutorecEntry(\n    id: String,",
        "public suspend fun HtspConnection.addTimerecEntry(\n    title: String,\n    channel: HtspRecordingRuleChannel? = null,",
        "public suspend fun HtspConnection.updateTimerecEntry(\n    id: String,\n    channel: HtspRecordingRuleChannel? = null,",
        "public suspend fun HtspConnection.deleteTimerecEntry(\n    id: String,",
        "public suspend fun HtspConnection.hello(\n    htspVersion: Long,\n    clientName: String,",
        "public suspend fun HtspConnection.authenticate(\n    timeoutMs: Long = 5_000L,",
    )
    missing = [signature for signature in required_signatures if signature not in first]
    if missing:
        raise AssertionError(f"generated extension signatures are incomplete: {missing}")
    if first.count("    execute(") != 50:
        raise AssertionError("every generated extension must contain exactly one execute delegation")
    if "    call(" in first:
        raise AssertionError("generated extensions must not bypass public execute")
    if first.count("        timeoutMs = timeoutMs,") != 50:
        raise AssertionError("every generated extension must forward timeout exactly once")
    if first.count("        expectedGeneration = expectedGeneration,") != 50:
        raise AssertionError("every generated extension must forward generation exactly once")
    if first.count("request = SubscriptionSkipRequest(") != 3:
        raise AssertionError("subscriptionSkip must emit one canonical and two selector overload request constructions")
    if first.count("request = HelloRequest(") != 1 or first.count("request = AuthenticateRequest(),") != 1:
        raise AssertionError("handshake extensions must each construct exactly one finite request")
    if first.count("request = ApiRequest(") != 1 or first.count("@HtspJsonApi") != 1:
        raise AssertionError("api extension must construct one finite request and require its opt-in")
    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "generated.kt"
        path.write_text(first, encoding="utf-8")
        if path.read_text(encoding="utf-8") != first:
            raise AssertionError("temporary output round-trip drifted")


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    validate_catalog()
    if args.self_test:
        self_test()
        return 0
    generated = render()
    if args.write:
        OUTPUT.write_text(generated, encoding="utf-8")
        return 0
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
        raise SystemExit(f"generated typed HTSP request source is stale: {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
