#!/usr/bin/env python3
"""Generate the reviewed 20-request HTSP convenience/catalog surface."""

from __future__ import annotations

import argparse
import tempfile
from dataclasses import dataclass
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT = (
    SCRIPT_DIR.parents[1]
    / "sdk/htsp/src/main/kotlin/at/bernhardberger/tvheadend/htsp/GeneratedHtspExtensions.kt"
)


@dataclass(frozen=True)
class Entry:
    method: str
    request: str
    response: str
    access: str
    minimum_version: int | None
    default_request: bool = False


# Reviewed constructor/type authority. Never derive this catalog from source literals.
CATALOG: tuple[Entry, ...] = (
    Entry("getProfiles", "GetProfilesRequest", "GetProfilesResponse", "ACCESS_HTSP_STREAMING", 16, True),
    Entry("getDiskSpace", "GetDiskSpaceRequest", "GetDiskSpaceResponse", "ACCESS_HTSP_STREAMING", 3, True),
    Entry("getSysTime", "GetSysTimeRequest", "GetSysTimeResponse", "ACCESS_HTSP_STREAMING", 3, True),
    Entry("getChannel", "GetChannelRequest", "GetChannelResponse", "ACCESS_HTSP_STREAMING", 14),
    Entry("getEvent", "GetEventRequest", "GetEventResponse", "ACCESS_HTSP_STREAMING", None),
    Entry("getEvents", "GetEventsRequest", "GetEventsResponse", "ACCESS_HTSP_STREAMING", 4),
    Entry("getDvrConfigs", "GetDvrConfigsRequest", "GetDvrConfigsResponse", "ACCESS_HTSP_RECORDER", 16, True),
    Entry("addDvrEntry", "AddDvrEntryRequest", "AddDvrEntryResponse", "ACCESS_HTSP_RECORDER", 4),
    Entry("updateDvrEntry", "UpdateDvrEntryRequest", "UpdateDvrEntryResponse", "ACCESS_HTSP_RECORDER", 5),
    Entry("stopDvrEntry", "StopDvrEntryRequest", "StopDvrEntryResponse", "ACCESS_HTSP_RECORDER", None),
    Entry("cancelDvrEntry", "CancelDvrEntryRequest", "CancelDvrEntryResponse", "ACCESS_HTSP_RECORDER", 5),
    Entry("deleteDvrEntry", "DeleteDvrEntryRequest", "DeleteDvrEntryResponse", "ACCESS_HTSP_RECORDER", 4),
    Entry("getDvrCutpoints", "GetDvrCutpointsRequest", "GetDvrCutpointsResponse", "ACCESS_HTSP_RECORDER", 12),
    Entry("subscribe", "SubscribeRequest", "SubscribeResponse", "ACCESS_HTSP_STREAMING", None),
    Entry("unsubscribe", "UnsubscribeRequest", "HtspEmptyResponse", "ACCESS_HTSP_STREAMING", None),
    Entry("subscriptionChangeWeight", "SubscriptionChangeWeightRequest", "HtspEmptyResponse", "ACCESS_HTSP_STREAMING", 5),
    Entry("subscriptionSeek", "SubscriptionSeekRequest", "HtspEmptyResponse", "ACCESS_HTSP_STREAMING", 9),
    Entry("subscriptionSpeed", "SubscriptionSpeedRequest", "HtspEmptyResponse", "ACCESS_HTSP_STREAMING", 9),
    Entry("subscriptionLive", "SubscriptionLiveRequest", "HtspEmptyResponse", "ACCESS_HTSP_STREAMING", 9),
    Entry("subscriptionFilterStream", "SubscriptionFilterStreamRequest", "HtspEmptyResponse", "ACCESS_HTSP_STREAMING", 12),
)


def render() -> str:
    lines = [
        "// Generated by docs/htsp-protocol/generate_typed_requests.py. DO NOT EDIT.",
        "// The reviewed catalog in that generator is the request/response constructor authority.",
        "package at.bernhardberger.tvheadend.htsp",
        "",
        "internal data class TypedHtspRequestCatalogEntry(",
        "    val method: String,",
        "    val requestType: String,",
        "    val responseType: String,",
        "    val access: HtspAccess,",
        "    val minimumProtocolVersion: Int?,",
        ")",
        "",
        "internal val typedHtspRequestCatalog: List<TypedHtspRequestCatalogEntry> = listOf(",
    ]
    for entry in CATALOG:
        version = "null" if entry.minimum_version is None else str(entry.minimum_version)
        lines.append(
            f'    TypedHtspRequestCatalogEntry("{entry.method}", "{entry.request}", '
            f'"{entry.response}", HtspAccess.{entry.access}, {version}),'
        )
    lines.extend((")", ""))
    for entry in CATALOG:
        default = f" = {entry.request}()" if entry.default_request else ""
        lines.append(
            f"public suspend fun HtspConnection.{entry.method}(request: {entry.request}{default}): "
            f"HtspResult<{entry.response}> = call(request)"
        )
    lines.append("")
    return "\n".join(lines)


def validate_catalog() -> None:
    expected = (
        "getProfiles", "getDiskSpace", "getSysTime", "getChannel", "getEvent",
        "getEvents", "getDvrConfigs", "addDvrEntry", "updateDvrEntry", "stopDvrEntry",
        "cancelDvrEntry", "deleteDvrEntry", "getDvrCutpoints", "subscribe", "unsubscribe",
        "subscriptionChangeWeight", "subscriptionSeek", "subscriptionSpeed",
        "subscriptionLive", "subscriptionFilterStream",
    )
    methods = tuple(entry.method for entry in CATALOG)
    if methods != expected or len(set(methods)) != 20:
        raise ValueError("typed request catalog must contain exactly the reviewed 20 methods")
    forbidden = {"hello", "authenticate", "enableAsyncMetadata", "subscriptionSkip", "fileOpen"}
    if forbidden.intersection(methods):
        raise ValueError("typed request catalog contains an excluded method")


def self_test() -> None:
    validate_catalog()
    first = render()
    second = render()
    if first != second:
        raise AssertionError("generator output is not deterministic")
    extension_lines = [line for line in first.splitlines() if line.startswith("public suspend fun")]
    if len(extension_lines) != 20 or any(" = call(request)" not in line for line in extension_lines):
        raise AssertionError("generated extensions must be exactly 20 one-line delegations")
    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "generated.kt"
        path.write_text(first, encoding="utf-8")
        if path.read_text(encoding="utf-8") != first:
            raise AssertionError("temporary output round-trip drifted")


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    validate_catalog()
    if args.self_test:
        self_test()
        return 0
    generated = render()
    if args.write:
        OUTPUT.write_text(generated, encoding="utf-8")
        return 0
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
        raise SystemExit(f"generated typed HTSP request source is stale: {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
