// Generated by docs/htsp-protocol/generate_typed_request_models.py. DO NOT EDIT.
// The reviewed semantic catalog is docs/htsp-protocol/htsp_surface.py.
package at.bernhardberger.tvheadend.htsp.jsonapi

import at.bernhardberger.tvheadend.htsp.requests.HtspAccess
import at.bernhardberger.tvheadend.htsp.requests.HtspRequest

/** Exact endpoint invocation transported through the provisional HTSP JSON API bridge. */
@HtspJsonApi
public data class ApiRequest(
    public val path: String,
    public val args: HtspApiObject? = null,
) : HtspRequest<ApiResponse>(
    method = "api",
    access = HtspAccess.ACCESS_ANONYMOUS,
    minimumProtocolVersion = 24,
)

/** Finite successful reply topology for the provisional HTSP JSON API bridge. */
@HtspJsonApi
public sealed interface ApiResponse {
    /** A successful map or list payload. */
    @HtspJsonApi
    public data class Payload(public val value: HtspApiContainer) : ApiResponse

    /** A successful callback that supplied no response payload. */
    @HtspJsonApi
    public data object NoPayload : ApiResponse
}
