// Generated by docs/htsp-protocol/generate_typed_requests.py. DO NOT EDIT.
// docs/htsp-protocol/htsp_surface.py is the reviewed request/response constructor authority.
@file:JvmName("GeneratedHtspExtensionsKt")

package at.bernhardberger.tvheadend.htsp.jsonapi

import at.bernhardberger.tvheadend.htsp.connection.*

@HtspJsonApi
public suspend fun HtspConnection.api(
    path: String,
    args: HtspApiObject? = null,
    timeoutMs: Long = 5_000L,
    expectedGeneration: HtspConnectionGeneration? = null,
): HtspResult<ApiResponse> =
    execute(
        request = ApiRequest(
            path = path,
            args = args,
        ),
        timeoutMs = timeoutMs,
        expectedGeneration = expectedGeneration,
    )
